//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace myRaiServiceHub.it.rai.servizi.hrpaga {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HrPagaSoap", Namespace="HrPaga")]
    public partial class HrPaga : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerificaUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoMessaggiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoNavBarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoMenuBarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoTipoDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoDocumentiOldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoDocumentiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoDocumentiPersonaliOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoNotificheOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoNotificheDocumentiOperationCompleted;
        
        private System.Threading.SendOrPostCallback AggiornaNotificheOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambiaStatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambiaStatoOldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaDocumentiCassaOldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaDocumentiCassaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ByteDocOldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ByteDocPersonaliOperationCompleted;
        
        private System.Threading.SendOrPostCallback ByteDocOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HrPaga() {
            this.Url = global::myRaiServiceHub.Properties.Settings.Default.myRaiServiceHub_it_rai_servizi_hrpaga_HrPaga;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VerificaUserCompletedEventHandler VerificaUserCompleted;
        
        /// <remarks/>
        public event ElencoMessaggiCompletedEventHandler ElencoMessaggiCompleted;
        
        /// <remarks/>
        public event ElencoNavBarCompletedEventHandler ElencoNavBarCompleted;
        
        /// <remarks/>
        public event ElencoMenuBarCompletedEventHandler ElencoMenuBarCompleted;
        
        /// <remarks/>
        public event ElencoTipoDocumentoCompletedEventHandler ElencoTipoDocumentoCompleted;
        
        /// <remarks/>
        public event ElencoDocumentiOldCompletedEventHandler ElencoDocumentiOldCompleted;
        
        /// <remarks/>
        public event ElencoDocumentiCompletedEventHandler ElencoDocumentiCompleted;
        
        /// <remarks/>
        public event ElencoDocumentiPersonaliCompletedEventHandler ElencoDocumentiPersonaliCompleted;
        
        /// <remarks/>
        public event ElencoNotificheCompletedEventHandler ElencoNotificheCompleted;
        
        /// <remarks/>
        public event ElencoNotificheDocumentiCompletedEventHandler ElencoNotificheDocumentiCompleted;
        
        /// <remarks/>
        public event AggiornaNotificheCompletedEventHandler AggiornaNotificheCompleted;
        
        /// <remarks/>
        public event CambiaStatoCompletedEventHandler CambiaStatoCompleted;
        
        /// <remarks/>
        public event CambiaStatoOldCompletedEventHandler CambiaStatoOldCompleted;
        
        /// <remarks/>
        public event ListaDocumentiCassaOldCompletedEventHandler ListaDocumentiCassaOldCompleted;
        
        /// <remarks/>
        public event ListaDocumentiCassaCompletedEventHandler ListaDocumentiCassaCompleted;
        
        /// <remarks/>
        public event ByteDocOldCompletedEventHandler ByteDocOldCompleted;
        
        /// <remarks/>
        public event ByteDocPersonaliCompletedEventHandler ByteDocPersonaliCompleted;
        
        /// <remarks/>
        public event ByteDocCompletedEventHandler ByteDocCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/VerificaUser", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificaUser(string chiamante) {
            object[] results = this.Invoke("VerificaUser", new object[] {
                        chiamante});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerificaUserAsync(string chiamante) {
            this.VerificaUserAsync(chiamante, null);
        }
        
        /// <remarks/>
        public void VerificaUserAsync(string chiamante, object userState) {
            if ((this.VerificaUserOperationCompleted == null)) {
                this.VerificaUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificaUserOperationCompleted);
            }
            this.InvokeAsync("VerificaUser", new object[] {
                        chiamante}, this.VerificaUserOperationCompleted, userState);
        }
        
        private void OnVerificaUserOperationCompleted(object arg) {
            if ((this.VerificaUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificaUserCompleted(this, new VerificaUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoMessaggi", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaMessaggi ElencoMessaggi() {
            object[] results = this.Invoke("ElencoMessaggi", new object[0]);
            return ((ListaMessaggi)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoMessaggiAsync() {
            this.ElencoMessaggiAsync(null);
        }
        
        /// <remarks/>
        public void ElencoMessaggiAsync(object userState) {
            if ((this.ElencoMessaggiOperationCompleted == null)) {
                this.ElencoMessaggiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoMessaggiOperationCompleted);
            }
            this.InvokeAsync("ElencoMessaggi", new object[0], this.ElencoMessaggiOperationCompleted, userState);
        }
        
        private void OnElencoMessaggiOperationCompleted(object arg) {
            if ((this.ElencoMessaggiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoMessaggiCompleted(this, new ElencoMessaggiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoNavBar", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaNavBar ElencoNavBar() {
            object[] results = this.Invoke("ElencoNavBar", new object[0]);
            return ((ListaNavBar)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoNavBarAsync() {
            this.ElencoNavBarAsync(null);
        }
        
        /// <remarks/>
        public void ElencoNavBarAsync(object userState) {
            if ((this.ElencoNavBarOperationCompleted == null)) {
                this.ElencoNavBarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoNavBarOperationCompleted);
            }
            this.InvokeAsync("ElencoNavBar", new object[0], this.ElencoNavBarOperationCompleted, userState);
        }
        
        private void OnElencoNavBarOperationCompleted(object arg) {
            if ((this.ElencoNavBarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoNavBarCompleted(this, new ElencoNavBarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoMenuBar", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaNavBar ElencoMenuBar(string Matricola) {
            object[] results = this.Invoke("ElencoMenuBar", new object[] {
                        Matricola});
            return ((ListaNavBar)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoMenuBarAsync(string Matricola) {
            this.ElencoMenuBarAsync(Matricola, null);
        }
        
        /// <remarks/>
        public void ElencoMenuBarAsync(string Matricola, object userState) {
            if ((this.ElencoMenuBarOperationCompleted == null)) {
                this.ElencoMenuBarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoMenuBarOperationCompleted);
            }
            this.InvokeAsync("ElencoMenuBar", new object[] {
                        Matricola}, this.ElencoMenuBarOperationCompleted, userState);
        }
        
        private void OnElencoMenuBarOperationCompleted(object arg) {
            if ((this.ElencoMenuBarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoMenuBarCompleted(this, new ElencoMenuBarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoTipoDocumento", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaNavBar ElencoTipoDocumento() {
            object[] results = this.Invoke("ElencoTipoDocumento", new object[0]);
            return ((ListaNavBar)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoTipoDocumentoAsync() {
            this.ElencoTipoDocumentoAsync(null);
        }
        
        /// <remarks/>
        public void ElencoTipoDocumentoAsync(object userState) {
            if ((this.ElencoTipoDocumentoOperationCompleted == null)) {
                this.ElencoTipoDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoTipoDocumentoOperationCompleted);
            }
            this.InvokeAsync("ElencoTipoDocumento", new object[0], this.ElencoTipoDocumentoOperationCompleted, userState);
        }
        
        private void OnElencoTipoDocumentoOperationCompleted(object arg) {
            if ((this.ElencoTipoDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoTipoDocumentoCompleted(this, new ElencoTipoDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoDocumentiOld", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaDocumenti ElencoDocumentiOld(string parametro_01, string parametro_02) {
            object[] results = this.Invoke("ElencoDocumentiOld", new object[] {
                        parametro_01,
                        parametro_02});
            return ((ListaDocumenti)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoDocumentiOldAsync(string parametro_01, string parametro_02) {
            this.ElencoDocumentiOldAsync(parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void ElencoDocumentiOldAsync(string parametro_01, string parametro_02, object userState) {
            if ((this.ElencoDocumentiOldOperationCompleted == null)) {
                this.ElencoDocumentiOldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoDocumentiOldOperationCompleted);
            }
            this.InvokeAsync("ElencoDocumentiOld", new object[] {
                        parametro_01,
                        parametro_02}, this.ElencoDocumentiOldOperationCompleted, userState);
        }
        
        private void OnElencoDocumentiOldOperationCompleted(object arg) {
            if ((this.ElencoDocumentiOldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoDocumentiOldCompleted(this, new ElencoDocumentiOldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoDocumenti", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaDocumenti ElencoDocumenti(string parametro_01, string parametro_02) {
            object[] results = this.Invoke("ElencoDocumenti", new object[] {
                        parametro_01,
                        parametro_02});
            return ((ListaDocumenti)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoDocumentiAsync(string parametro_01, string parametro_02) {
            this.ElencoDocumentiAsync(parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void ElencoDocumentiAsync(string parametro_01, string parametro_02, object userState) {
            if ((this.ElencoDocumentiOperationCompleted == null)) {
                this.ElencoDocumentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoDocumentiOperationCompleted);
            }
            this.InvokeAsync("ElencoDocumenti", new object[] {
                        parametro_01,
                        parametro_02}, this.ElencoDocumentiOperationCompleted, userState);
        }
        
        private void OnElencoDocumentiOperationCompleted(object arg) {
            if ((this.ElencoDocumentiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoDocumentiCompleted(this, new ElencoDocumentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoDocumentiPersonali", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaDocumenti ElencoDocumentiPersonali(string parametro_tipo, string parametro_01, string parametro_02) {
            object[] results = this.Invoke("ElencoDocumentiPersonali", new object[] {
                        parametro_tipo,
                        parametro_01,
                        parametro_02});
            return ((ListaDocumenti)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoDocumentiPersonaliAsync(string parametro_tipo, string parametro_01, string parametro_02) {
            this.ElencoDocumentiPersonaliAsync(parametro_tipo, parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void ElencoDocumentiPersonaliAsync(string parametro_tipo, string parametro_01, string parametro_02, object userState) {
            if ((this.ElencoDocumentiPersonaliOperationCompleted == null)) {
                this.ElencoDocumentiPersonaliOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoDocumentiPersonaliOperationCompleted);
            }
            this.InvokeAsync("ElencoDocumentiPersonali", new object[] {
                        parametro_tipo,
                        parametro_01,
                        parametro_02}, this.ElencoDocumentiPersonaliOperationCompleted, userState);
        }
        
        private void OnElencoDocumentiPersonaliOperationCompleted(object arg) {
            if ((this.ElencoDocumentiPersonaliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoDocumentiPersonaliCompleted(this, new ElencoDocumentiPersonaliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoNotifiche", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaNotifiche ElencoNotifiche(string parametro_01, string parametro_02) {
            object[] results = this.Invoke("ElencoNotifiche", new object[] {
                        parametro_01,
                        parametro_02});
            return ((ListaNotifiche)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoNotificheAsync(string parametro_01, string parametro_02) {
            this.ElencoNotificheAsync(parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void ElencoNotificheAsync(string parametro_01, string parametro_02, object userState) {
            if ((this.ElencoNotificheOperationCompleted == null)) {
                this.ElencoNotificheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoNotificheOperationCompleted);
            }
            this.InvokeAsync("ElencoNotifiche", new object[] {
                        parametro_01,
                        parametro_02}, this.ElencoNotificheOperationCompleted, userState);
        }
        
        private void OnElencoNotificheOperationCompleted(object arg) {
            if ((this.ElencoNotificheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoNotificheCompleted(this, new ElencoNotificheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ElencoNotificheDocumenti", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaNotificheDocumenti ElencoNotificheDocumenti(string parametro_01, string parametro_02, string parametro_03) {
            object[] results = this.Invoke("ElencoNotificheDocumenti", new object[] {
                        parametro_01,
                        parametro_02,
                        parametro_03});
            return ((ListaNotificheDocumenti)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoNotificheDocumentiAsync(string parametro_01, string parametro_02, string parametro_03) {
            this.ElencoNotificheDocumentiAsync(parametro_01, parametro_02, parametro_03, null);
        }
        
        /// <remarks/>
        public void ElencoNotificheDocumentiAsync(string parametro_01, string parametro_02, string parametro_03, object userState) {
            if ((this.ElencoNotificheDocumentiOperationCompleted == null)) {
                this.ElencoNotificheDocumentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoNotificheDocumentiOperationCompleted);
            }
            this.InvokeAsync("ElencoNotificheDocumenti", new object[] {
                        parametro_01,
                        parametro_02,
                        parametro_03}, this.ElencoNotificheDocumentiOperationCompleted, userState);
        }
        
        private void OnElencoNotificheDocumentiOperationCompleted(object arg) {
            if ((this.ElencoNotificheDocumentiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoNotificheDocumentiCompleted(this, new ElencoNotificheDocumentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/AggiornaNotifiche", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaNotifiche AggiornaNotifiche(string parametro_01, string parametro_02) {
            object[] results = this.Invoke("AggiornaNotifiche", new object[] {
                        parametro_01,
                        parametro_02});
            return ((ListaNotifiche)(results[0]));
        }
        
        /// <remarks/>
        public void AggiornaNotificheAsync(string parametro_01, string parametro_02) {
            this.AggiornaNotificheAsync(parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void AggiornaNotificheAsync(string parametro_01, string parametro_02, object userState) {
            if ((this.AggiornaNotificheOperationCompleted == null)) {
                this.AggiornaNotificheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAggiornaNotificheOperationCompleted);
            }
            this.InvokeAsync("AggiornaNotifiche", new object[] {
                        parametro_01,
                        parametro_02}, this.AggiornaNotificheOperationCompleted, userState);
        }
        
        private void OnAggiornaNotificheOperationCompleted(object arg) {
            if ((this.AggiornaNotificheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AggiornaNotificheCompleted(this, new AggiornaNotificheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/CambiaStato", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EsitoBlocco CambiaStato(string parametro_record1, string parametro_record2, int parametro_record3, string parametro_record4, string parametro_01, string parametro_02) {
            object[] results = this.Invoke("CambiaStato", new object[] {
                        parametro_record1,
                        parametro_record2,
                        parametro_record3,
                        parametro_record4,
                        parametro_01,
                        parametro_02});
            return ((EsitoBlocco)(results[0]));
        }
        
        /// <remarks/>
        public void CambiaStatoAsync(string parametro_record1, string parametro_record2, int parametro_record3, string parametro_record4, string parametro_01, string parametro_02) {
            this.CambiaStatoAsync(parametro_record1, parametro_record2, parametro_record3, parametro_record4, parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void CambiaStatoAsync(string parametro_record1, string parametro_record2, int parametro_record3, string parametro_record4, string parametro_01, string parametro_02, object userState) {
            if ((this.CambiaStatoOperationCompleted == null)) {
                this.CambiaStatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambiaStatoOperationCompleted);
            }
            this.InvokeAsync("CambiaStato", new object[] {
                        parametro_record1,
                        parametro_record2,
                        parametro_record3,
                        parametro_record4,
                        parametro_01,
                        parametro_02}, this.CambiaStatoOperationCompleted, userState);
        }
        
        private void OnCambiaStatoOperationCompleted(object arg) {
            if ((this.CambiaStatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambiaStatoCompleted(this, new CambiaStatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/CambiaStatoOld", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EsitoBlocco CambiaStatoOld(string parametro_record1, string parametro_record2, int parametro_record3, string parametro_record4, string parametro_01, string parametro_02) {
            object[] results = this.Invoke("CambiaStatoOld", new object[] {
                        parametro_record1,
                        parametro_record2,
                        parametro_record3,
                        parametro_record4,
                        parametro_01,
                        parametro_02});
            return ((EsitoBlocco)(results[0]));
        }
        
        /// <remarks/>
        public void CambiaStatoOldAsync(string parametro_record1, string parametro_record2, int parametro_record3, string parametro_record4, string parametro_01, string parametro_02) {
            this.CambiaStatoOldAsync(parametro_record1, parametro_record2, parametro_record3, parametro_record4, parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void CambiaStatoOldAsync(string parametro_record1, string parametro_record2, int parametro_record3, string parametro_record4, string parametro_01, string parametro_02, object userState) {
            if ((this.CambiaStatoOldOperationCompleted == null)) {
                this.CambiaStatoOldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambiaStatoOldOperationCompleted);
            }
            this.InvokeAsync("CambiaStatoOld", new object[] {
                        parametro_record1,
                        parametro_record2,
                        parametro_record3,
                        parametro_record4,
                        parametro_01,
                        parametro_02}, this.CambiaStatoOldOperationCompleted, userState);
        }
        
        private void OnCambiaStatoOldOperationCompleted(object arg) {
            if ((this.CambiaStatoOldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambiaStatoOldCompleted(this, new CambiaStatoOldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ListaDocumentiCassaOld", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaDocumentiPerCassa ListaDocumentiCassaOld(string parametro_tipo, string parametro_record1, string parametro_record2, string parametro_record3, int parametro_record4, string[] parametro_record5, System.DateTime[] parametro_record6, System.DateTime[] parametro_record7, string parametro_02) {
            object[] results = this.Invoke("ListaDocumentiCassaOld", new object[] {
                        parametro_tipo,
                        parametro_record1,
                        parametro_record2,
                        parametro_record3,
                        parametro_record4,
                        parametro_record5,
                        parametro_record6,
                        parametro_record7,
                        parametro_02});
            return ((ListaDocumentiPerCassa)(results[0]));
        }
        
        /// <remarks/>
        public void ListaDocumentiCassaOldAsync(string parametro_tipo, string parametro_record1, string parametro_record2, string parametro_record3, int parametro_record4, string[] parametro_record5, System.DateTime[] parametro_record6, System.DateTime[] parametro_record7, string parametro_02) {
            this.ListaDocumentiCassaOldAsync(parametro_tipo, parametro_record1, parametro_record2, parametro_record3, parametro_record4, parametro_record5, parametro_record6, parametro_record7, parametro_02, null);
        }
        
        /// <remarks/>
        public void ListaDocumentiCassaOldAsync(string parametro_tipo, string parametro_record1, string parametro_record2, string parametro_record3, int parametro_record4, string[] parametro_record5, System.DateTime[] parametro_record6, System.DateTime[] parametro_record7, string parametro_02, object userState) {
            if ((this.ListaDocumentiCassaOldOperationCompleted == null)) {
                this.ListaDocumentiCassaOldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaDocumentiCassaOldOperationCompleted);
            }
            this.InvokeAsync("ListaDocumentiCassaOld", new object[] {
                        parametro_tipo,
                        parametro_record1,
                        parametro_record2,
                        parametro_record3,
                        parametro_record4,
                        parametro_record5,
                        parametro_record6,
                        parametro_record7,
                        parametro_02}, this.ListaDocumentiCassaOldOperationCompleted, userState);
        }
        
        private void OnListaDocumentiCassaOldOperationCompleted(object arg) {
            if ((this.ListaDocumentiCassaOldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaDocumentiCassaOldCompleted(this, new ListaDocumentiCassaOldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ListaDocumentiCassa", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaDocumentiPerCassa ListaDocumentiCassa(string parametro_tipo, string parametro_record1, string parametro_record2, string parametro_record3, int parametro_record4, string[] parametro_record5, System.DateTime[] parametro_record6, System.DateTime[] parametro_record7, string parametro_02) {
            object[] results = this.Invoke("ListaDocumentiCassa", new object[] {
                        parametro_tipo,
                        parametro_record1,
                        parametro_record2,
                        parametro_record3,
                        parametro_record4,
                        parametro_record5,
                        parametro_record6,
                        parametro_record7,
                        parametro_02});
            return ((ListaDocumentiPerCassa)(results[0]));
        }
        
        /// <remarks/>
        public void ListaDocumentiCassaAsync(string parametro_tipo, string parametro_record1, string parametro_record2, string parametro_record3, int parametro_record4, string[] parametro_record5, System.DateTime[] parametro_record6, System.DateTime[] parametro_record7, string parametro_02) {
            this.ListaDocumentiCassaAsync(parametro_tipo, parametro_record1, parametro_record2, parametro_record3, parametro_record4, parametro_record5, parametro_record6, parametro_record7, parametro_02, null);
        }
        
        /// <remarks/>
        public void ListaDocumentiCassaAsync(string parametro_tipo, string parametro_record1, string parametro_record2, string parametro_record3, int parametro_record4, string[] parametro_record5, System.DateTime[] parametro_record6, System.DateTime[] parametro_record7, string parametro_02, object userState) {
            if ((this.ListaDocumentiCassaOperationCompleted == null)) {
                this.ListaDocumentiCassaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaDocumentiCassaOperationCompleted);
            }
            this.InvokeAsync("ListaDocumentiCassa", new object[] {
                        parametro_tipo,
                        parametro_record1,
                        parametro_record2,
                        parametro_record3,
                        parametro_record4,
                        parametro_record5,
                        parametro_record6,
                        parametro_record7,
                        parametro_02}, this.ListaDocumentiCassaOperationCompleted, userState);
        }
        
        private void OnListaDocumentiCassaOperationCompleted(object arg) {
            if ((this.ListaDocumentiCassaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaDocumentiCassaCompleted(this, new ListaDocumentiCassaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ByteDocOld", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Documento ByteDocOld(string id, string parametro_01, string parametro_02) {
            object[] results = this.Invoke("ByteDocOld", new object[] {
                        id,
                        parametro_01,
                        parametro_02});
            return ((Documento)(results[0]));
        }
        
        /// <remarks/>
        public void ByteDocOldAsync(string id, string parametro_01, string parametro_02) {
            this.ByteDocOldAsync(id, parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void ByteDocOldAsync(string id, string parametro_01, string parametro_02, object userState) {
            if ((this.ByteDocOldOperationCompleted == null)) {
                this.ByteDocOldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnByteDocOldOperationCompleted);
            }
            this.InvokeAsync("ByteDocOld", new object[] {
                        id,
                        parametro_01,
                        parametro_02}, this.ByteDocOldOperationCompleted, userState);
        }
        
        private void OnByteDocOldOperationCompleted(object arg) {
            if ((this.ByteDocOldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ByteDocOldCompleted(this, new ByteDocOldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ByteDocPersonali", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Documento ByteDocPersonali(string id, string parametro_01, string parametro_02) {
            object[] results = this.Invoke("ByteDocPersonali", new object[] {
                        id,
                        parametro_01,
                        parametro_02});
            return ((Documento)(results[0]));
        }
        
        /// <remarks/>
        public void ByteDocPersonaliAsync(string id, string parametro_01, string parametro_02) {
            this.ByteDocPersonaliAsync(id, parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void ByteDocPersonaliAsync(string id, string parametro_01, string parametro_02, object userState) {
            if ((this.ByteDocPersonaliOperationCompleted == null)) {
                this.ByteDocPersonaliOperationCompleted = new System.Threading.SendOrPostCallback(this.OnByteDocPersonaliOperationCompleted);
            }
            this.InvokeAsync("ByteDocPersonali", new object[] {
                        id,
                        parametro_01,
                        parametro_02}, this.ByteDocPersonaliOperationCompleted, userState);
        }
        
        private void OnByteDocPersonaliOperationCompleted(object arg) {
            if ((this.ByteDocPersonaliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ByteDocPersonaliCompleted(this, new ByteDocPersonaliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HrPaga/ByteDoc", RequestNamespace="HrPaga", ResponseNamespace="HrPaga", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Documento ByteDoc(string id, string parametro_01, string parametro_02) {
            object[] results = this.Invoke("ByteDoc", new object[] {
                        id,
                        parametro_01,
                        parametro_02});
            return ((Documento)(results[0]));
        }
        
        /// <remarks/>
        public void ByteDocAsync(string id, string parametro_01, string parametro_02) {
            this.ByteDocAsync(id, parametro_01, parametro_02, null);
        }
        
        /// <remarks/>
        public void ByteDocAsync(string id, string parametro_01, string parametro_02, object userState) {
            if ((this.ByteDocOperationCompleted == null)) {
                this.ByteDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnByteDocOperationCompleted);
            }
            this.InvokeAsync("ByteDoc", new object[] {
                        id,
                        parametro_01,
                        parametro_02}, this.ByteDocOperationCompleted, userState);
        }
        
        private void OnByteDocOperationCompleted(object arg) {
            if ((this.ByteDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ByteDocCompleted(this, new ByteDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class ListaMessaggi {
        
        private string stringaErroreField;
        
        private int esitoField;
        
        private string[] messaggioField;
        
        /// <remarks/>
        public string StringaErrore {
            get {
                return this.stringaErroreField;
            }
            set {
                this.stringaErroreField = value;
            }
        }
        
        /// <remarks/>
        public int Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        public string[] Messaggio {
            get {
                return this.messaggioField;
            }
            set {
                this.messaggioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class Documento {
        
        private string stringaErroreField;
        
        private int esitoField;
        
        private byte[] fileDocField;
        
        /// <remarks/>
        public string StringaErrore {
            get {
                return this.stringaErroreField;
            }
            set {
                this.stringaErroreField = value;
            }
        }
        
        /// <remarks/>
        public int Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileDoc {
            get {
                return this.fileDocField;
            }
            set {
                this.fileDocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class DocumentoInCassa {
        
        private string matricolaField;
        
        private string tipoCedolinoField;
        
        private System.DateTime dataCompetenzaField;
        
        private System.DateTime dataContabileField;
        
        private string sedeField;
        
        private string servizioField;
        
        private string categoriaField;
        
        private string nomeField;
        
        private string cognomeField;
        
        private string importoField;
        
        private string casisticaField;
        
        private int eliminatoField;
        
        private int idField;
        
        private string idDettaglioField;
        
        private int flagBloccoField;
        
        private string iDIMGField;
        
        /// <remarks/>
        public string Matricola {
            get {
                return this.matricolaField;
            }
            set {
                this.matricolaField = value;
            }
        }
        
        /// <remarks/>
        public string TipoCedolino {
            get {
                return this.tipoCedolinoField;
            }
            set {
                this.tipoCedolinoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCompetenza {
            get {
                return this.dataCompetenzaField;
            }
            set {
                this.dataCompetenzaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataContabile {
            get {
                return this.dataContabileField;
            }
            set {
                this.dataContabileField = value;
            }
        }
        
        /// <remarks/>
        public string Sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
            }
        }
        
        /// <remarks/>
        public string Servizio {
            get {
                return this.servizioField;
            }
            set {
                this.servizioField = value;
            }
        }
        
        /// <remarks/>
        public string Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
            }
        }
        
        /// <remarks/>
        public string Importo {
            get {
                return this.importoField;
            }
            set {
                this.importoField = value;
            }
        }
        
        /// <remarks/>
        public string Casistica {
            get {
                return this.casisticaField;
            }
            set {
                this.casisticaField = value;
            }
        }
        
        /// <remarks/>
        public int Eliminato {
            get {
                return this.eliminatoField;
            }
            set {
                this.eliminatoField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string idDettaglio {
            get {
                return this.idDettaglioField;
            }
            set {
                this.idDettaglioField = value;
            }
        }
        
        /// <remarks/>
        public int FlagBlocco {
            get {
                return this.flagBloccoField;
            }
            set {
                this.flagBloccoField = value;
            }
        }
        
        /// <remarks/>
        public string IDIMG {
            get {
                return this.iDIMGField;
            }
            set {
                this.iDIMGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class ListaDocumentiPerCassa {
        
        private string stringaErroreField;
        
        private int esitoField;
        
        private DocumentoInCassa[] documentoInCassaField;
        
        /// <remarks/>
        public string StringaErrore {
            get {
                return this.stringaErroreField;
            }
            set {
                this.stringaErroreField = value;
            }
        }
        
        /// <remarks/>
        public int Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentoInCassa")]
        public DocumentoInCassa[] DocumentoInCassa {
            get {
                return this.documentoInCassaField;
            }
            set {
                this.documentoInCassaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class EsitoBlocco {
        
        private string stringaErroreField;
        
        private int esitoField;
        
        /// <remarks/>
        public string StringaErrore {
            get {
                return this.stringaErroreField;
            }
            set {
                this.stringaErroreField = value;
            }
        }
        
        /// <remarks/>
        public int Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class ListaNotificheDocumenti {
        
        private string stringaErroreField;
        
        private int esitoField;
        
        private string notificheField;
        
        /// <remarks/>
        public string StringaErrore {
            get {
                return this.stringaErroreField;
            }
            set {
                this.stringaErroreField = value;
            }
        }
        
        /// <remarks/>
        public int Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        public string Notifiche {
            get {
                return this.notificheField;
            }
            set {
                this.notificheField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class Notifica {
        
        private string pmatricolaField;
        
        private int numeroDocumentiField;
        
        /// <remarks/>
        public string Pmatricola {
            get {
                return this.pmatricolaField;
            }
            set {
                this.pmatricolaField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroDocumenti {
            get {
                return this.numeroDocumentiField;
            }
            set {
                this.numeroDocumentiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class ListaNotifiche {
        
        private string stringaErroreField;
        
        private int esitoField;
        
        private Notifica[] notificheField;
        
        /// <remarks/>
        public string StringaErrore {
            get {
                return this.stringaErroreField;
            }
            set {
                this.stringaErroreField = value;
            }
        }
        
        /// <remarks/>
        public int Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Notifica[] Notifiche {
            get {
                return this.notificheField;
            }
            set {
                this.notificheField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class ListaDatiDocumenti {
        
        private string dataCompetenzaField;
        
        private string descrittivaDataCompetenzaField;
        
        private string dataContabileField;
        
        private string descrittivaDataContabileField;
        
        private string descrittivaField;
        
        private string descrittivaTipoDocField;
        
        private string messaggioCollegatoField;
        
        private string dataPubblicazioneField;
        
        private string notaField;
        
        private int flagLettoField;
        
        private int flagToolbarField;
        
        private int flagStampaField;
        
        private int flagBloccoField;
        
        private string tipoCedolinoField;
        
        private string idField;
        
        /// <remarks/>
        public string DataCompetenza {
            get {
                return this.dataCompetenzaField;
            }
            set {
                this.dataCompetenzaField = value;
            }
        }
        
        /// <remarks/>
        public string DescrittivaDataCompetenza {
            get {
                return this.descrittivaDataCompetenzaField;
            }
            set {
                this.descrittivaDataCompetenzaField = value;
            }
        }
        
        /// <remarks/>
        public string DataContabile {
            get {
                return this.dataContabileField;
            }
            set {
                this.dataContabileField = value;
            }
        }
        
        /// <remarks/>
        public string DescrittivaDataContabile {
            get {
                return this.descrittivaDataContabileField;
            }
            set {
                this.descrittivaDataContabileField = value;
            }
        }
        
        /// <remarks/>
        public string Descrittiva {
            get {
                return this.descrittivaField;
            }
            set {
                this.descrittivaField = value;
            }
        }
        
        /// <remarks/>
        public string DescrittivaTipoDoc {
            get {
                return this.descrittivaTipoDocField;
            }
            set {
                this.descrittivaTipoDocField = value;
            }
        }
        
        /// <remarks/>
        public string MessaggioCollegato {
            get {
                return this.messaggioCollegatoField;
            }
            set {
                this.messaggioCollegatoField = value;
            }
        }
        
        /// <remarks/>
        public string DataPubblicazione {
            get {
                return this.dataPubblicazioneField;
            }
            set {
                this.dataPubblicazioneField = value;
            }
        }
        
        /// <remarks/>
        public string Nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
            }
        }
        
        /// <remarks/>
        public int FlagLetto {
            get {
                return this.flagLettoField;
            }
            set {
                this.flagLettoField = value;
            }
        }
        
        /// <remarks/>
        public int FlagToolbar {
            get {
                return this.flagToolbarField;
            }
            set {
                this.flagToolbarField = value;
            }
        }
        
        /// <remarks/>
        public int FlagStampa {
            get {
                return this.flagStampaField;
            }
            set {
                this.flagStampaField = value;
            }
        }
        
        /// <remarks/>
        public int FlagBlocco {
            get {
                return this.flagBloccoField;
            }
            set {
                this.flagBloccoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoCedolino {
            get {
                return this.tipoCedolinoField;
            }
            set {
                this.tipoCedolinoField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class ListaDocumenti {
        
        private string stringaErroreField;
        
        private int esitoField;
        
        private ListaDatiDocumenti[] listaDatiDocumentiField;
        
        /// <remarks/>
        public string StringaErrore {
            get {
                return this.stringaErroreField;
            }
            set {
                this.stringaErroreField = value;
            }
        }
        
        /// <remarks/>
        public int Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListaDatiDocumenti")]
        public ListaDatiDocumenti[] ListaDatiDocumenti {
            get {
                return this.listaDatiDocumentiField;
            }
            set {
                this.listaDatiDocumentiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="HrPaga")]
    public partial class ListaNavBar {
        
        private string stringaErroreField;
        
        private int esitoField;
        
        private string[] elementiField;
        
        /// <remarks/>
        public string StringaErrore {
            get {
                return this.stringaErroreField;
            }
            set {
                this.stringaErroreField = value;
            }
        }
        
        /// <remarks/>
        public int Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        public string[] Elementi {
            get {
                return this.elementiField;
            }
            set {
                this.elementiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void VerificaUserCompletedEventHandler(object sender, VerificaUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificaUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificaUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoMessaggiCompletedEventHandler(object sender, ElencoMessaggiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoMessaggiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoMessaggiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaMessaggi Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaMessaggi)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoNavBarCompletedEventHandler(object sender, ElencoNavBarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoNavBarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoNavBarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaNavBar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaNavBar)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoMenuBarCompletedEventHandler(object sender, ElencoMenuBarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoMenuBarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoMenuBarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaNavBar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaNavBar)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoTipoDocumentoCompletedEventHandler(object sender, ElencoTipoDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoTipoDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoTipoDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaNavBar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaNavBar)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoDocumentiOldCompletedEventHandler(object sender, ElencoDocumentiOldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoDocumentiOldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoDocumentiOldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaDocumenti Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaDocumenti)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoDocumentiCompletedEventHandler(object sender, ElencoDocumentiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoDocumentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoDocumentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaDocumenti Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaDocumenti)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoDocumentiPersonaliCompletedEventHandler(object sender, ElencoDocumentiPersonaliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoDocumentiPersonaliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoDocumentiPersonaliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaDocumenti Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaDocumenti)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoNotificheCompletedEventHandler(object sender, ElencoNotificheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoNotificheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoNotificheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaNotifiche Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaNotifiche)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ElencoNotificheDocumentiCompletedEventHandler(object sender, ElencoNotificheDocumentiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoNotificheDocumentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoNotificheDocumentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaNotificheDocumenti Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaNotificheDocumenti)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AggiornaNotificheCompletedEventHandler(object sender, AggiornaNotificheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AggiornaNotificheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AggiornaNotificheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaNotifiche Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaNotifiche)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CambiaStatoCompletedEventHandler(object sender, CambiaStatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CambiaStatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambiaStatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EsitoBlocco Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EsitoBlocco)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CambiaStatoOldCompletedEventHandler(object sender, CambiaStatoOldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CambiaStatoOldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambiaStatoOldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EsitoBlocco Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EsitoBlocco)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListaDocumentiCassaOldCompletedEventHandler(object sender, ListaDocumentiCassaOldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaDocumentiCassaOldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaDocumentiCassaOldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaDocumentiPerCassa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaDocumentiPerCassa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListaDocumentiCassaCompletedEventHandler(object sender, ListaDocumentiCassaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaDocumentiCassaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaDocumentiCassaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaDocumentiPerCassa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaDocumentiPerCassa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ByteDocOldCompletedEventHandler(object sender, ByteDocOldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ByteDocOldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ByteDocOldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Documento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Documento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ByteDocPersonaliCompletedEventHandler(object sender, ByteDocPersonaliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ByteDocPersonaliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ByteDocPersonaliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Documento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Documento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ByteDocCompletedEventHandler(object sender, ByteDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ByteDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ByteDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Documento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Documento)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591