//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CZNMMDOC
    {
        public int ID_CZNMMDOC { get; set; }
        public Nullable<int> ID_DATASOURCE { get; set; }
        public Nullable<int> ID_LANG { get; set; }
        public Nullable<int> ID_DOCSCAT { get; set; }
        public string NME_FILENAME { get; set; }
        public string DES_CZNMMDOC { get; set; }
        public string COD_EXTENSION { get; set; }
        public byte[] OBJ_OBJECT { get; set; }
        public int NBR_FILESIZE { get; set; }
        public string IND_PRIVATE { get; set; }
        public string NME_ATTACHNAME { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public string NOT_CZNMMDOC { get; set; }
        public int NBR_SOURCETYPE { get; set; }
        public Nullable<int> ID_DATASET { get; set; }
        public string IND_FACTORY { get; set; }
        public string COD_GROUP { get; set; }
        public int NBR_CLEAROPTION { get; set; }
        public int NBR_TARGETTYPE { get; set; }
        public string NME_BOREPORTNAME { get; set; }
        public string COD_INSERTUSER { get; set; }
        public string IND_STANDALONE { get; set; }
    }
}
