//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETASSAZIONE
    {
        public int Id { get; set; }
        public string Matricola { get; set; }
        public int Anno { get; set; }
        public string CodiceDetassazione { get; set; }
        public Nullable<System.DateTime> DataCompilazione { get; set; }
        public string Modello { get; set; }
        public string Scelta { get; set; }
        public string Nominativo { get; set; }
        public string ModelloAssegnato { get; set; }
        public string Applicazione { get; set; }
        public Nullable<int> Giorni { get; set; }
        public Nullable<int> RAL { get; set; }
        public string Categoria { get; set; }
        public byte[] Pdf { get; set; }
        public Nullable<System.DateTime> DataLettura { get; set; }
    }
}
