//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDITIONCALENDAR
    {
        public int ID_EDITIONCALENDAR { get; set; }
        public int ID_EDIZIONE { get; set; }
        public System.DateTime DTA_DATE { get; set; }
        public short NMB_FROMHOUR { get; set; }
        public short NMB_TOHOUR { get; set; }
        public short NMB_FROMMINUTE { get; set; }
        public short NMB_TOMINUTE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public Nullable<decimal> NMB_HOURS { get; set; }
    
        public virtual EDIZIONE EDIZIONE { get; set; }
    }
}
