//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_STRGROUP
    {
        public int ID_STRGROUP { get; set; }
        public string COD_IMPRESA { get; set; }
        public string COD_DIVISA { get; set; }
        public string COD_IMPRESAPADRE { get; set; }
        public string COD_TIPOIMPRESA { get; set; }
        public string IND_CONTRIBACC { get; set; }
        public string COD_ISO { get; set; }
        public string CFS_CODFISCIMP { get; set; }
        public short PRG_SORT { get; set; }
        public string PIV_PIVASOCIETA { get; set; }
        public string NOT_SOGGETTO { get; set; }
        public string COD_LINGUA { get; set; }
        public string DES_ISCRTRIB { get; set; }
        public string DES_ISCRCCOM { get; set; }
        public decimal IMP_CAPSOCIALE { get; set; }
        public string NOT_SHAREHOLDERS { get; set; }
        public decimal IMP_CAPITALSHARET { get; set; }
        public decimal IMP_CAPITALISSUED { get; set; }
        public decimal IMP_CAPITALPARVAL { get; set; }
        public string NOT_EXTAUDITORS { get; set; }
        public string DES_YEAREND { get; set; }
        public string NOT_BYLAWSART { get; set; }
        public string NOT_LOCSHARECERT { get; set; }
        public string NOT_LOCORGCORPDOC { get; set; }
        public string DES_CONSOLMETHOD { get; set; }
        public string NOT_NATUREOPER { get; set; }
        public string NOT_PURPOSE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    }
}
