//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ATENEO
    {
        public TB_ATENEO()
        {
            this.STUPERSONA = new HashSet<STUPERSONA>();
        }
    
        public string COD_ATENEO { get; set; }
        public string COD_CITTA { get; set; }
        public string DES_ATENEO { get; set; }
        public short QTA_ORDINE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    
        public virtual ICollection<STUPERSONA> STUPERSONA { get; set; }
        public virtual TB_COMUNE TB_COMUNE { get; set; }
    }
}
