//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CDC
    {
        public int ID_CDC { get; set; }
        public string COD_CDC { get; set; }
        public string COD_TPCDC { get; set; }
        public string DES_CDC { get; set; }
        public short QTA_ORDINE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public Nullable<int> ID_STRSAMPLE { get; set; }
        public Nullable<int> ID_SAMPLE { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO { get; set; }
        public Nullable<System.DateTime> DTA_FINE { get; set; }
    }
}
