//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QUALSTD
    {
        public TB_QUALSTD()
        {
            this.QUALIFICA = new HashSet<QUALIFICA>();
        }
    
        public string COD_QUALSTD { get; set; }
        public string DES_QUALSTD { get; set; }
        public short QTA_ORDINE { get; set; }
        public string IND_WEBVISIBLE { get; set; }
        public short QTA_WEIGHT { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    
        public virtual ICollection<QUALIFICA> QUALIFICA { get; set; }
    }
}
