//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TPCORSO
    {
        public TB_TPCORSO()
        {
            this.CORSO = new HashSet<CORSO>();
        }
    
        public int ID_TPCORSO { get; set; }
        public string COD_TIPOCORSO { get; set; }
        public string DES_TIPOCORSO { get; set; }
        public short QTA_ORDINE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public Nullable<int> ID_COURSEPROVIDER { get; set; }
        public string IND_ELEARNING { get; set; }
    
        public virtual ICollection<CORSO> CORSO { get; set; }
    }
}
