//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_CORSOINTPERSONA
    {
        public int ID_CORSOINTPERSONA { get; set; }
        public int ID_PERSONA { get; set; }
        public string MATRICOLA { get; set; }
        public int ID_CORSO { get; set; }
    
        public virtual CORSO CORSO { get; set; }
    }
}
