//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_STATO_RAPPORTO_INFO
    {
        public int ID_INFO { get; set; }
        public int ID_STATO_RAPPORTO { get; set; }
        public System.DateTime DTA_INIZIO { get; set; }
        public Nullable<System.DateTime> DTA_FINE { get; set; }
        public Nullable<int> NUM_GIORNI_MAX { get; set; }
        public System.DateTime VALID_DTA_INI { get; set; }
        public Nullable<System.DateTime> VALID_DTA_END { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public Nullable<int> NUM_GIORNI_MIN { get; set; }
        public Nullable<int> NUM_GIORNI_EXTRA { get; set; }
        public string IPOTESI_FRAGILI { get; set; }
        public Nullable<System.DateTime> DTA_INVIO { get; set; }
        public Nullable<System.DateTime> DTA_VISITA_MEDICA { get; set; }
        public Nullable<int> ID_RICH { get; set; }
        public Nullable<int> NUM_GIORNI_MAX_ORIG { get; set; }
        public Nullable<int> NUM_GIORNI_MIN_ORIG { get; set; }
        public Nullable<int> NUM_GIORNI_EXTRA_ORIG { get; set; }
    
        public virtual XR_STATO_RAPPORTO XR_STATO_RAPPORTO { get; set; }
    }
}
