//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_STR_TINCARICO
    {
        public int id_incarico { get; set; }
        public int id_sezione { get; set; }
        public string matricola { get; set; }
        public string nominativo { get; set; }
        public string data_inizio_validita { get; set; }
        public string data_fine_validita { get; set; }
        public string cod_incarico { get; set; }
        public string flag_resp { get; set; }
        public string cod_user { get; set; }
        public string cod_termid { get; set; }
        public Nullable<System.DateTime> tms_timestamp { get; set; }
        public string note_incarico { get; set; }
        public string incarico_personalizzato { get; set; }
    }
}
