//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiDataTalentia
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_TB_STATO_RAPPORTO
    {
        public XR_TB_STATO_RAPPORTO()
        {
            this.XR_STATO_RAPPORTO = new HashSet<XR_STATO_RAPPORTO>();
        }
    
        public string COD_STATO_RAPPORTO { get; set; }
        public string DES_STATO_RAPPORTO { get; set; }
        public int ORDINE { get; set; }
        public bool IND_VISUALIZZA { get; set; }
    
        public virtual ICollection<XR_STATO_RAPPORTO> XR_STATO_RAPPORTO { get; set; }
    }
}
