//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2RaiPlace_RaiPlacePolicy
    {
        public B2RaiPlace_RaiPlacePolicy()
        {
            this.B2RaiPlace_RaiPlacePolicyUtenti = new HashSet<B2RaiPlace_RaiPlacePolicyUtenti>();
        }
    
        public int Id_RaiPlacePolicy { get; set; }
        public string Testo { get; set; }
        public Nullable<System.DateTime> Versione { get; set; }
        public string Societa { get; set; }
        public byte[] pdf { get; set; }
    
        public virtual ICollection<B2RaiPlace_RaiPlacePolicyUtenti> B2RaiPlace_RaiPlacePolicyUtenti { get; set; }
    }
}
