//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2RaiPlace_RegistroOmaggi_Omaggio
    {
        public int Id { get; set; }
        public int Id_Utente { get; set; }
        public System.DateTime Data_Ricezione { get; set; }
        public int Id_Motivo_Omaggio { get; set; }
        public string Mittente { get; set; }
        public int Id_Tipo_Omaggio { get; set; }
        public string Descrizione { get; set; }
        public decimal Valore { get; set; }
        public bool Flag_UfficioSpedizioni { get; set; }
        public string Id_UfficioSpedizioni { get; set; }
        public string Ente_Beneficiario { get; set; }
        public string Note { get; set; }
        public bool Flag_validita { get; set; }
        public System.DateTime Data_Inserimento { get; set; }
        public string Mail_Responsabile { get; set; }
        public Nullable<bool> Flag_accetto { get; set; }
        public string Note_accetto { get; set; }
        public string Note_Motivo { get; set; }
    
        public virtual B2RaiPlace_RegistroOmaggi_Anagrafica B2RaiPlace_RegistroOmaggi_Anagrafica { get; set; }
        public virtual B2RaiPlace_RegistroOmaggi_Motivo B2RaiPlace_RegistroOmaggi_Motivo { get; set; }
        public virtual B2RaiPlace_RegistroOmaggi_Tipo B2RaiPlace_RegistroOmaggi_Tipo { get; set; }
    }
}
