//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2RaiPlace_Cestini_Richieste
    {
        public int Id_richiesta { get; set; }
        public int Id_ordine { get; set; }
        public int Progressivo { get; set; }
        public bool Flag_tipo_risorsa { get; set; }
        public string Matricola_risorsa { get; set; }
        public string Cognome_risorsa { get; set; }
        public string Nome_risorsa { get; set; }
        public string Motivo_esterno { get; set; }
        public int Id_tipo_cestino { get; set; }
        public System.DateTime Data_inserimento { get; set; }
        public string Codice_richiesta { get; set; }
        public string Note_richiesta { get; set; }
    
        public virtual B2RaiPlace_Cestini_Ordini B2RaiPlace_Cestini_Ordini { get; set; }
        public virtual B2RaiPlace_Cestini_Tipologie B2RaiPlace_Cestini_Tipologie { get; set; }
    }
}
