//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2RaiPlace_Cestini_Status_Ordini
    {
        public B2RaiPlace_Cestini_Status_Ordini()
        {
            this.B2RaiPlace_Cestini_Ordini = new HashSet<B2RaiPlace_Cestini_Ordini>();
        }
    
        public int Id { get; set; }
        public string Descrizione { get; set; }
    
        public virtual ICollection<B2RaiPlace_Cestini_Ordini> B2RaiPlace_Cestini_Ordini { get; set; }
    }
}
