//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catena_Hotel
    {
        public string Id_Catena_Hotel { get; set; }
        public string Nome_Catena_Hotel { get; set; }
        public string Codice_Cliente { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Sito { get; set; }
        public string Tipo_Catena { get; set; }
        public string Flag_Attivo { get; set; }
        public string Note { get; set; }
    }
}
