//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convenzioni
    {
        public int Id_Convenzione { get; set; }
        public string Id_Hotel { get; set; }
        public string Data_Inizio { get; set; }
        public string Data_Fine { get; set; }
        public string Ulteriori_Informazioni { get; set; }
        public string Note { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
