//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCompDigitLiv
    {
        public string CodCompDigit { get; set; }
        public string CodCompDigitLiv { get; set; }
        public string DescCompDigitLiv { get; set; }
        public string DescCompDigitLivLunga { get; set; }
    }
}
