//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRPADBEntities : DbContext
    {
        public HRPADBEntities()
            : base("name=HRPADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_SkCarburantiDoc> T_SkCarburantiDoc { get; set; }
        public DbSet<T_SkCarburantiDati> T_SkCarburantiDati { get; set; }
        public DbSet<T_SkCarburantiParam> T_SkCarburantiParam { get; set; }
        public DbSet<TRION_Richiedenti> TRION_Richiedenti { get; set; }
        public DbSet<TRION_Richieste> TRION_Richieste { get; set; }
        public DbSet<TSOGG_Soggiorno> TSOGG_Soggiorno { get; set; }
        public DbSet<TSOGG_Richiedente> TSOGG_Richiedente { get; set; }
        public DbSet<THRPA_Stati> THRPA_Stati { get; set; }
        public DbSet<TSOGG_SchedaConsuntivi> TSOGG_SchedaConsuntivi { get; set; }
        public DbSet<TRION_Partecipanti> TRION_Partecipanti { get; set; }
        public DbSet<TSOGG_Partecipanti> TSOGG_Partecipanti { get; set; }
        public DbSet<TSOGG_ValutazioniSogg> TSOGG_ValutazioniSogg { get; set; }
        public DbSet<T_SkCarburantiAssegnatari> T_SkCarburantiAssegnatari { get; set; }
        public DbSet<T_DetaxNew> T_DetaxNew { get; set; }
        public DbSet<T_SkCarburantiAlim> T_SkCarburantiAlim { get; set; }
        public DbSet<TTFR_ENTEPREVCOMPL> TTFR_ENTEPREVCOMPL { get; set; }
    }
}
