//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alberghiEntities : DbContext
    {
        public alberghiEntities()
            : base("name=alberghiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Catena_Hotel> Catena_Hotel { get; set; }
        public DbSet<Città> Città { get; set; }
        public DbSet<Convenzioni> Convenzioni { get; set; }
        public DbSet<Documenti> Documenti { get; set; }
        public DbSet<Hotel> Hotel { get; set; }
        public DbSet<Hotel_Catena> Hotel_Catena { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Note> Note { get; set; }
        public DbSet<Prezzi> Prezzi { get; set; }
        public DbSet<Prezzi_Validità> Prezzi_Validità { get; set; }
        public DbSet<Province> Province { get; set; }
        public DbSet<Recapiti> Recapiti { get; set; }
        public DbSet<Regioni> Regioni { get; set; }
        public DbSet<Tipo_Recapito> Tipo_Recapito { get; set; }
        public DbSet<Tipologia_Camera> Tipologia_Camera { get; set; }
    }
}
