//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_Pianificazione
    {
        public int id { get; set; }
        public System.DateTime Data { get; set; }
        public string Eccezione { get; set; }
        public string Matricola { get; set; }
        public string SedeGapp { get; set; }
        public System.DateTime DataInserimento { get; set; }
        public string Tipologia { get; set; }
        public Nullable<System.DateTime> DataApprovazione { get; set; }
        public Nullable<System.DateTime> DataRifiuto { get; set; }
        public string MatricolaApprovatore { get; set; }
        public string Note { get; set; }
        public string InseritoDa { get; set; }
        public string Errore { get; set; }
        public Nullable<System.DateTime> ErroreData { get; set; }
    }
}
