//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_Note_Richieste
    {
        public int Id { get; set; }
        public string Mittente { get; set; }
        public string Destinatario { get; set; }
        public string Visualizzatore { get; set; }
        public string DescrizioneVisualizzatore { get; set; }
        public string Messaggio { get; set; }
        public System.DateTime DataCreazione { get; set; }
        public System.DateTime DataUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataLettura { get; set; }
        public System.DateTime DataGiornata { get; set; }
        public string DescrizioneMittente { get; set; }
        public string SedeGapp { get; set; }
    }
}
