//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_RimborsiRMTR
    {
        public int id { get; set; }
        public string sedegapp { get; set; }
        public string giorno_settimana { get; set; }
        public string dalle { get; set; }
        public string alle { get; set; }
        public string importo_rimborso { get; set; }
    }
}
