//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_FormRisposteDate
    {
        public int id { get; set; }
        public int id_domanda { get; set; }
        public Nullable<int> id_risposta { get; set; }
        public string risposta_text { get; set; }
        public string matricola { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual MyRai_FormRispostePossibili MyRai_FormRispostePossibili { get; set; }
        public virtual MyRai_FormDomande MyRai_FormDomande { get; set; }
    }
}
