//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_StatiWizardFS
    {
        public MyRai_StatiWizardFS()
        {
            this.MyRai_WizardFS = new HashSet<MyRai_WizardFS>();
        }
    
        public int id { get; set; }
        public string stato { get; set; }
    
        public virtual MyRai_StatiWizardFS MyRai_StatiWizardFS1 { get; set; }
        public virtual MyRai_StatiWizardFS MyRai_StatiWizardFS2 { get; set; }
        public virtual ICollection<MyRai_WizardFS> MyRai_WizardFS { get; set; }
    }
}
