//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_ParametriSistema
    {
        public long Id { get; set; }
        public string Chiave { get; set; }
        public string Valore1 { get; set; }
        public string Valore2 { get; set; }
        public string Categoria_Parametri { get; set; }
    }
}
