//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_InfoDipendente_Tipologia
    {
        public MyRai_InfoDipendente_Tipologia()
        {
            this.MyRai_InfoDipendente = new HashSet<MyRai_InfoDipendente>();
        }
    
        public int id { get; set; }
        public string info { get; set; }
        public System.DateTime data_inizio { get; set; }
        public Nullable<System.DateTime> data_fine { get; set; }
        public string note { get; set; }
        public string tipo_valore { get; set; }
    
        public virtual ICollection<MyRai_InfoDipendente> MyRai_InfoDipendente { get; set; }
    }
}
