//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_CoperturaCarenze
    {
        public int id { get; set; }
        public System.DateTime data_eccezione { get; set; }
        public string matricola { get; set; }
        public string cod_eccezione { get; set; }
        public string dalle { get; set; }
        public string alle { get; set; }
        public int minuti_intervallo { get; set; }
        public int minuti_totali { get; set; }
        public System.DateTime data_inserimento { get; set; }
        public string note { get; set; }
        public Nullable<int> id_richiesta { get; set; }
    }
}
