//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_LogAzioni
    {
        public int Id { get; set; }
        public string matricola { get; set; }
        public System.DateTime data { get; set; }
        public string operazione { get; set; }
        public string descrizione_operazione { get; set; }
        public string applicativo { get; set; }
        public string provenienza { get; set; }
    }
}
