//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_Trasferte_ProgViaggio
    {
        public long Id { get; set; }
        public string PROCID { get; set; }
        public string PRONUMPRAT { get; set; }
        public string PRODNUMVERS { get; set; }
        public string PRODNUMPOS { get; set; }
        public string PRODCODPREN { get; set; }
        public string PRODATAARRIVO { get; set; }
        public string PROORAARRIVO { get; set; }
        public string PRONUMPROGR { get; set; }
        public string PROAGCOD { get; set; }
        public string PROPRATEV { get; set; }
        public string CODE_ADV { get; set; }
        public string CDC { get; set; }
        public string PRODPNR { get; set; }
        public string PRODTIPOSERVIZIO { get; set; }
        public string PRODORIGINE { get; set; }
        public string PRODDATAIN { get; set; }
        public string PRODORAIN { get; set; }
        public string PRODDESTCITTA { get; set; }
        public string PRODDATAOUT { get; set; }
        public string PRODORAOUT { get; set; }
        public string PRODDESTPAESE { get; set; }
        public string PRODVOLONUM { get; set; }
        public string PRODCLASSE { get; set; }
        public string PRODFORNITORE { get; set; }
        public string PRODFLAGBIGLELET { get; set; }
        public string PRODPROGADV { get; set; }
        public string PRODSTATUS { get; set; }
    }
}
