//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_InvioMail
    {
        public MyRai_InvioMail()
        {
            this.MyRai_InvioMail_Allegati = new HashSet<MyRai_InvioMail_Allegati>();
        }
    
        public int Id { get; set; }
        public string Mittente { get; set; }
        public string Destinatario { get; set; }
        public string DestinatarioCC { get; set; }
        public string Oggetto { get; set; }
        public string Body { get; set; }
        public bool FormatoHtml { get; set; }
        public int Priorita { get; set; }
        public System.DateTime DataUltimoTentativo { get; set; }
        public Nullable<bool> Esito { get; set; }
        public string Errore { get; set; }
        public Nullable<System.DateTime> DataProgrammata { get; set; }
        public int TentativiInvio { get; set; }
        public string DestinatariCCN { get; set; }
    
        public virtual ICollection<MyRai_InvioMail_Allegati> MyRai_InvioMail_Allegati { get; set; }
    }
}
