//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_MensaXML
    {
        public int id { get; set; }
        public string LocationID { get; set; }
        public string PosID { get; set; }
        public string TransactionID { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public int Total { get; set; }
        public string Badge { get; set; }
        public string XMLorig { get; set; }
    }
}
