//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_Abilita_VociMenu
    {
        public int ID { get; set; }
        public string Abilitato { get; set; }
        public int Id_Voce_Menu { get; set; }
        public Nullable<int> Tipo_Inc { get; set; }
    
        public virtual MyRai_Voci_Menu MyRai_Voci_Menu { get; set; }
    }
}
