//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_AttivitaCeiton
    {
        public MyRai_AttivitaCeiton()
        {
            this.MyRai_Richieste = new HashSet<MyRai_Richieste>();
        }
    
        public int id { get; set; }
        public string AttivitaPrimaria { get; set; }
        public string AttivitaSecondaria { get; set; }
        public string AttivitaSvolta { get; set; }
        public Nullable<System.DateTime> DataAttivita { get; set; }
        public string Matricola { get; set; }
        public string MatricolaResponsabile { get; set; }
        public string Note { get; set; }
        public string OraInizioAttivita { get; set; }
        public string OraFineAttivita { get; set; }
        public string Titolo { get; set; }
        public string Uorg { get; set; }
        public Nullable<System.DateTime> DataCreazione { get; set; }
        public string idCeiton { get; set; }
    
        public virtual ICollection<MyRai_Richieste> MyRai_Richieste { get; set; }
    }
}
