//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_Regole_Destinatari
    {
        public MyRai_Regole_Destinatari()
        {
            this.MyRai_Regole_SchedeEccezioni_Destinatari = new HashSet<MyRai_Regole_SchedeEccezioni_Destinatari>();
        }
    
        public int id { get; set; }
        public string destinatario { get; set; }
    
        public virtual ICollection<MyRai_Regole_SchedeEccezioni_Destinatari> MyRai_Regole_SchedeEccezioni_Destinatari { get; set; }
    }
}
