//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_LogAPI
    {
        public int id { get; set; }
        public System.DateTime Data { get; set; }
        public string API { get; set; }
        public string Parametri { get; set; }
        public string KeyString { get; set; }
        public string IP { get; set; }
        public string UserAgent { get; set; }
        public bool Authorized { get; set; }
    }
}
