//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_Voci_Menu
    {
        public MyRai_Voci_Menu()
        {
            this.MyRai_Abilita_VociMenu = new HashSet<MyRai_Abilita_VociMenu>();
            this.MyRai_Profili_Menu = new HashSet<MyRai_Profili_Menu>();
        }
    
        public int ID { get; set; }
        public string Titolo { get; set; }
        public string customView { get; set; }
        public string nomeSezione { get; set; }
        public string icon { get; set; }
        public Nullable<int> Id_Padre { get; set; }
        public string codiceMy { get; set; }
        public bool richiede_gapp { get; set; }
        public Nullable<int> progressivo { get; set; }
    
        public virtual ICollection<MyRai_Abilita_VociMenu> MyRai_Abilita_VociMenu { get; set; }
        public virtual ICollection<MyRai_Profili_Menu> MyRai_Profili_Menu { get; set; }
    }
}
