//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_MobileRegistration
    {
        public int id { get; set; }
        public string pmatricola { get; set; }
        public System.DateTime last_access { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> token_datetime { get; set; }
        public string device_id { get; set; }
        public string device_model { get; set; }
        public string device_manufacturer { get; set; }
        public string device_name { get; set; }
        public string device_platform { get; set; }
        public string device_version { get; set; }
        public string device_idiom { get; set; }
        public string device_type { get; set; }
        public string device_phonenbr { get; set; }
        public bool fingerprint_available { get; set; }
        public string auth_method { get; set; }
        public bool abilitato { get; set; }
    }
}
