//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public Note()
        {
            this.Hotel = new HashSet<Hotel>();
        }
    
        public string Id_Note { get; set; }
        public string Descrizione_Note { get; set; }
    
        public virtual ICollection<Hotel> Hotel { get; set; }
    }
}
