//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procuratori
    {
        public Procuratori()
        {
            this.Procure = new HashSet<Procure>();
        }
    
        public int Id_Procuratore { get; set; }
        public string Matricola { get; set; }
        public Nullable<System.DateTime> DataCessazione { get; set; }
        public int FlgRecord { get; set; }
        public Nullable<System.DateTime> DataAggiornamento { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public int FlgManuale { get; set; }
    
        public virtual ICollection<Procure> Procure { get; set; }
    }
}
