//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recapiti
    {
        public int Id_Recapito { get; set; }
        public string Id_Hotel { get; set; }
        public Nullable<int> Id_Tipo_Recapito { get; set; }
        public string Recapito { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Tipo_Recapito Tipo_Recapito { get; set; }
    }
}
