//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINTESI12
    {
        public int ID_PERSONA { get; set; }
        public string COD_CITTANASC { get; set; }
        public string DES_CITTANASC { get; set; }
        public string COD_STCIV { get; set; }
        public string DES_STCIV { get; set; }
        public string CSF_CFSPERSONA { get; set; }
        public string DES_TITOLOONOR { get; set; }
        public string DES_COGNOMEPERS { get; set; }
        public string DES_SECCOGNOME { get; set; }
        public string DES_COGNOMEACQ { get; set; }
        public string DES_NOMEPERS { get; set; }
        public Nullable<System.DateTime> DTA_NASCITAPERS { get; set; }
        public string COD_SESSO { get; set; }
        public string COD_POSMIL { get; set; }
        public string DES_POSMIL { get; set; }
        public string DES_CELLULARE { get; set; }
        public string COD_CITTADOM { get; set; }
        public string DES_CITTADOM { get; set; }
        public string DES_TELDOM { get; set; }
        public string CAP_CAPDOM { get; set; }
        public string DES_INDIRDOM { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_RES { get; set; }
        public string COD_CITTARES { get; set; }
        public string DES_CITTARES { get; set; }
        public string DES_TELRESID { get; set; }
        public string CAP_CAPRESID { get; set; }
        public string DES_INDIRRESID { get; set; }
        public Nullable<System.DateTime> DTA_FINE_RES { get; set; }
        public string COD_CITTASTUD { get; set; }
        public string DES_CITTASTUD { get; set; }
        public string COD_STUDIO { get; set; }
        public string DES_STUDIO { get; set; }
        public string COD_PUNTEGGIO { get; set; }
        public Nullable<System.DateTime> DTA_CONSEG { get; set; }
        public string COD_IMPRESA { get; set; }
        public string COD_SOGGETTO { get; set; }
        public string COD_MATLIBROMAT { get; set; }
        public string IND_LIBROMAT { get; set; }
        public Nullable<int> ID_ASSQUAL { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_Q { get; set; }
        public Nullable<System.DateTime> DTA_FINE_Q { get; set; }
        public string COD_QUALIFICA { get; set; }
        public string DES_QUALIFICA { get; set; }
        public Nullable<int> ID_STATO { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_S { get; set; }
        public Nullable<System.DateTime> DTA_FINE_S { get; set; }
        public string COD_STATORAPP { get; set; }
        public string DES_STATORAPP { get; set; }
        public Nullable<int> ID_INCARLAV { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_I { get; set; }
        public Nullable<System.DateTime> DTA_FINE_I { get; set; }
        public Nullable<int> ID_POSTOORG { get; set; }
        public string COD_POSTOORG { get; set; }
        public string DES_NOMEPOSTOORG { get; set; }
        public string IND_RESP { get; set; }
        public Nullable<int> ID_CDCREL { get; set; }
        public Nullable<int> ID_CDC { get; set; }
        public string COD_CDC { get; set; }
        public string DES_CDC { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_CDC { get; set; }
        public Nullable<System.DateTime> DTA_FINE_CDC { get; set; }
        public Nullable<int> ID_TRASF_SEDE { get; set; }
        public string COD_SEDE { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_SEDE { get; set; }
        public Nullable<System.DateTime> DTA_FINE_SEDE { get; set; }
        public string COD_CITTASEDE { get; set; }
        public string DES_CITTASEDE { get; set; }
        public string DES_SEDE { get; set; }
        public string DES_INDIRSEDE { get; set; }
        public string CAP_SEDE { get; set; }
        public string DES_TELSEDE { get; set; }
        public string DES_FAX { get; set; }
        public string DES_ELEMAIL { get; set; }
        public Nullable<int> ID_UNITAORG { get; set; }
        public string COD_UNITAORG { get; set; }
        public string DES_DENOMUNITAORG { get; set; }
        public Nullable<int> ID_JOBASSIGN { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_P { get; set; }
        public Nullable<System.DateTime> DTA_FINE_P { get; set; }
        public string COD_RUOLO { get; set; }
        public string DES_RUOLO { get; set; }
        public Nullable<int> ID_INQUACONTR { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_C { get; set; }
        public Nullable<System.DateTime> DTA_FINE_C { get; set; }
        public Nullable<int> ID_LIVRETR { get; set; }
        public string COD_CONTRRETR { get; set; }
        public string DES_CONTRRETR { get; set; }
        public string COD_LIVRETR { get; set; }
        public string DES_LIVRETR { get; set; }
        public Nullable<int> ID_PRESTEROG { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_M { get; set; }
        public Nullable<System.DateTime> DTA_FINE_M { get; set; }
        public string COD_MODERPRE { get; set; }
        public string DES_MODERPRE { get; set; }
        public Nullable<int> ID_COMPREL { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_CR { get; set; }
        public Nullable<System.DateTime> DTA_FINE_CR { get; set; }
        public Nullable<System.DateTime> DTA_ANZCONV { get; set; }
        public string COD_IMPRESACR { get; set; }
        public string COD_SOGGETTOCR { get; set; }
        public Nullable<int> ID_ASSTPCONTR { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_TPCNTR { get; set; }
        public Nullable<System.DateTime> DTA_FINE_TPCNTR { get; set; }
        public string COD_TPCNTR { get; set; }
        public string DES_TPCNTR { get; set; }
        public string COD_USER { get; set; }
        public Nullable<int> ID_JOBPROFILE { get; set; }
        public Nullable<int> ID_LOCATION { get; set; }
        public Nullable<decimal> ID_XR_SERVIZIO { get; set; }
        public string COD_SERVIZIO { get; set; }
        public string DES_SERVIZIO { get; set; }
        public string COD_EVSERVIZIO { get; set; }
        public string DES_EVSERVIZIO { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_XR { get; set; }
        public Nullable<System.DateTime> DTA_FINE_XR { get; set; }
    }
}
