//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bsf_Corsi
    {
        public string Anno_Bsf_Corsi { get; set; }
        public string Codice_Bsf_Corsi { get; set; }
        public string Descrittiva_Bsf_Corsi { get; set; }
        public string Param1_Bsf_Corsi { get; set; }
        public string Param2_Bsf_Corsi { get; set; }
        public string Param3_Bsf_Corsi { get; set; }
        public Nullable<int> Ord_Bsf_Corsi { get; set; }
        public Nullable<int> Importo_Bsf_Corsi { get; set; }
        public Nullable<int> ImportoOrigine_Bsf_Corsi { get; set; }
        public string Raggruppamento_Bsf_Corsi { get; set; }
    }
}
