//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SkCarburantiAssegnatari
    {
        public string matricola_SkCarburantiAssegnatari { get; set; }
        public System.DateTime decorrenza_SkCarburantiAssegnatari { get; set; }
        public Nullable<System.DateTime> scadenza_SkCarburantiAssegnatari { get; set; }
        public string societa_SkCarburantiAssegnatari { get; set; }
        public string nome_SkCarburantiAssegnatari { get; set; }
        public string tipodip_SkCarburantiAssegnatari { get; set; }
        public Nullable<decimal> litriplus_SkCarburantiAssegnatari { get; set; }
        public string note_SkCarburantiAssegnatari { get; set; }
        public string MessaggioPersonale_SkCarburantiAssegnatari { get; set; }
    }
}
