//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAbilitazione
    {
        public string login { get; set; }
        public string sede { get; set; }
        public string servizio { get; set; }
        public string livello_operativo { get; set; }
        public string flag_validita { get; set; }
    }
}
