//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCorsiCodice
    {
        public string codice_tbCorsiCodice { get; set; }
        public string anno_tbCorsiCodice { get; set; }
        public string edizione_tbCorsiCodice { get; set; }
        public string titolo_tbCorsiCodice { get; set; }
        public string inizio_tbCorsiCodice { get; set; }
        public string fine_tbCorsiCodice { get; set; }
        public Nullable<int> durata_tbCorsiCodice { get; set; }
        public Nullable<int> partecipanti_tbCorsiCodice { get; set; }
        public string fulltime_tbCorsiCodice { get; set; }
        public string luogo_tbCorsiCodice { get; set; }
        public string citta_tbCorsiCodice { get; set; }
        public string cap_tbCorsiCodice { get; set; }
        public string cod_ente_tbCorsiCodice { get; set; }
        public string svolgimento_tbCorsiCodice { get; set; }
        public string funzione_tbCorsiCodice { get; set; }
        public string destinatari_tbCorsiCodice { get; set; }
        public string note_tbCorsiCodice { get; set; }
        public string url_corso_tbCorsiCodice { get; set; }
        public string url_registrazione_tbCorsiCodice { get; set; }
        public string url_esito_tbCorsiCodice { get; set; }
    }
}
