//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCVEsperExRai
    {
        public string Matricola { get; set; }
        public int Prog { get; set; }
        public string DataInizio { get; set; }
        public string DataFine { get; set; }
        public string Societa { get; set; }
        public string AreaAtt { get; set; }
        public string UltRuolo { get; set; }
        public string Stato { get; set; }
        public string TipoAgg { get; set; }
        public Nullable<System.DateTime> DataOraAgg { get; set; }
        public string CodRedazione { get; set; }
        public string FlagEspRai { get; set; }
        public string FlagEspEstero { get; set; }
        public string CodContinente { get; set; }
        public string Nazione { get; set; }
        public string Direzione { get; set; }
        public string LocalitaEsp { get; set; }
        public string CodiceFiguraProf { get; set; }
        public string TitoloEspQual { get; set; }
        public string DescrizioneEsp { get; set; }
        public string CodDirezione { get; set; }
        public string CodSocieta { get; set; }
        public string CodProcura { get; set; }
        public string CodRisorseGest { get; set; }
        public string CodBudgetGest { get; set; }
        public string CodLocalitaEsp { get; set; }
        public string CodSettore { get; set; }
        public string Settore { get; set; }
        public string CodFigProExtra { get; set; }
        public string FigProExtra { get; set; }
    }
}
