//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCVEsperProd
    {
        public int ID_ESPERIENZE { get; set; }
        public string MATRICOLA { get; set; }
        public string COD_UORG { get; set; }
        public string COD_MATRICOLA { get; set; }
        public string COD_ANAGRAFIA { get; set; }
        public string DES_TITOLO_DEFINIT { get; set; }
        public string COD_UORG_BASE { get; set; }
        public string COD_GENERE { get; set; }
        public string COD_TIPO_SPETTACOL { get; set; }
        public Nullable<decimal> ANNO_PIANO { get; set; }
        public Nullable<decimal> NUM_PUNTATE_TX { get; set; }
        public string COD_FREQUENZA_PREV { get; set; }
        public string COD_STAGIONE_TELEV { get; set; }
        public string COD_FASCIA_COLLOCA { get; set; }
        public string ORA_FINE_TX { get; set; }
        public string ORA_INIZIO_TX { get; set; }
        public string COD_FASCIA_AUDITEL { get; set; }
        public Nullable<decimal> NUM_SHARE_PREV { get; set; }
        public Nullable<decimal> NUM_ASCOLTO_MEDIO { get; set; }
        public Nullable<decimal> COSTO_PREVISTO { get; set; }
        public Nullable<decimal> COSTO_CONSUNTIVO { get; set; }
        public string DESCRIZIONE_1 { get; set; }
        public string DESCRIZIONE_2 { get; set; }
        public string COD_RUOLO { get; set; }
        public string INIZIO_PERIODO_ESP { get; set; }
        public string FINE_PERIODO_ESP { get; set; }
        public string STATO_ALLOCAZIONE { get; set; }
        public Nullable<int> PERC_ASSEGNAZIONE { get; set; }
        public string DATA_SINCRO { get; set; }
        public string UTENTE { get; set; }
        public Nullable<System.DateTime> DATAGG { get; set; }
        public string TIPAGG { get; set; }
        public string TITOLO_PROVVISORIO { get; set; }
        public string CALCOLO_AUTOMATICO { get; set; }
    }
}
