//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCVFormExRai
    {
        public string Matricola { get; set; }
        public int Prog { get; set; }
        public string Corso { get; set; }
        public string Anno { get; set; }
        public string Durata { get; set; }
        public string Presso { get; set; }
        public string Stato { get; set; }
        public string TipoAgg { get; set; }
        public Nullable<System.DateTime> DataOraAgg { get; set; }
        public string LocalitaCorso { get; set; }
        public string CodNazione { get; set; }
        public string Note { get; set; }
    }
}
