//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCVSpecializz
    {
        public string Matricola { get; set; }
        public int Prog { get; set; }
        public string TipoSpecial { get; set; }
        public string Titolo { get; set; }
        public string Istituto { get; set; }
        public string Durata { get; set; }
        public string DataInizio { get; set; }
        public string DataFine { get; set; }
        public string Voto { get; set; }
        public string Scala { get; set; }
        public string Note { get; set; }
        public string Stato { get; set; }
        public string TipoAgg { get; set; }
        public Nullable<System.DateTime> DataOraAgg { get; set; }
        public string Lode { get; set; }
        public string LocalitaSpecial { get; set; }
        public string CodNazione { get; set; }
        public string IndirizzoSpecial { get; set; }
        public string Riconoscimento { get; set; }
        public string CodIstituto { get; set; }
    }
}
