//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFoglio_Spese
    {
        public decimal ID { get; set; }
        public System.DateTime Data_Creazione { get; set; }
        public string Gruppo_Emittente { get; set; }
        public string Struttura_Emittente { get; set; }
        public string Societa { get; set; }
        public string Divisione { get; set; }
        public string Matricola { get; set; }
        public string Stato { get; set; }
        public string Struttura_Appartenenza { get; set; }
        public string Categoria { get; set; }
        public string Livello { get; set; }
        public string Tipo_Contratto { get; set; }
        public decimal Foglio_Viaggio { get; set; }
        public string WBS { get; set; }
        public string CdC_Base { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public string II_Cognome { get; set; }
        public string Soc_SAP { get; set; }
        public string Uorg { get; set; }
        public string Tipo_Dip { get; set; }
        public string Sezione { get; set; }
        public string Fig_Prof { get; set; }
        public string Utente { get; set; }
        public System.DateTime DataAgg { get; set; }
        public string TipoAgg { get; set; }
    }
}
