//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class THRPA_Stati
    {
        public string APPL_TSTATI { get; set; }
        public string STATO_TSTATI { get; set; }
        public string DESCRBREVE_TSTATI { get; set; }
        public string DESCR_TSTATI { get; set; }
        public string NOTE_TSTATI { get; set; }
        public byte[] ICO_TSTATI { get; set; }
        public Nullable<int> SEQUENZA_TSTATI { get; set; }
    }
}
