//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLog
    {
        public int ID { get; set; }
        public System.DateTime DATA { get; set; }
        public string UTENTE { get; set; }
        public string DOVE { get; set; }
        public int ERR { get; set; }
        public string TESTO { get; set; }
    }
}
