//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPROCURATORI
    {
        public string CID { get; set; }
        public string SOCIETA { get; set; }
        public string AREA_APPARTENENZA { get; set; }
        public string RUOLO { get; set; }
        public System.DateTime DATA_CESSAZIONE { get; set; }
        public string COGNOME { get; set; }
        public string NOME { get; set; }
    }
}
