//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRION_Richiedenti
    {
        public int CodCatalogo_Richiedenti { get; set; }
        public int CodRichiesta_Richiedenti { get; set; }
        public string MatrRichiedente_Richiedenti { get; set; }
        public string Nominativo_Richiedenti { get; set; }
        public Nullable<int> ProgrRich_Richiedenti { get; set; }
        public string StrutturaRAI_Richiedenti { get; set; }
        public string Sede_Richiedenti { get; set; }
        public string IndUfficio_Richiedenti { get; set; }
        public string TelUfficio_Richiedenti { get; set; }
        public string Email_Richiedenti { get; set; }
        public string IndAbit_Richiedenti { get; set; }
        public string CapAbit_Richiedenti { get; set; }
        public string ProvinciaAbit_Richiedenti { get; set; }
        public string ComuneAbit_Richiedenti { get; set; }
        public string TelCasa_Richiedenti { get; set; }
        public string Cellulare_Richiedenti { get; set; }
        public string CodFiscale_Richiedenti { get; set; }
        public string TipoDipendente_Richiedenti { get; set; }
        public Nullable<int> NumOspiti_Richiedenti { get; set; }
        public Nullable<int> TotPartecipanti_Richiedenti { get; set; }
        public string ChkSospeso_Richiedenti { get; set; }
        public string PunteggioArcal_Richiedenti { get; set; }
        public string FlagUnicaSoluz_Richiedenti { get; set; }
        public string FlagAccCond_Richiedenti { get; set; }
        public string FlagAccPrivac_Richiedenti { get; set; }
        public string Note_Richiedenti { get; set; }
        public string UserID_Richiedenti { get; set; }
        public string DataOraUpd_Richiedenti { get; set; }
        public string AEM1_Richiedenti { get; set; }
        public string AEM2_Richiedenti { get; set; }
        public string AEM3_Richiedenti { get; set; }
        public string AEM4_Richiedenti { get; set; }
        public string InternetPDF { get; set; }
    }
}
