//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRION_Partecipanti
    {
        public int CodCatalogo_Partecipanti { get; set; }
        public int CodRichiesta_Partecipanti { get; set; }
        public int FlagSecondaScelta_Partecipanti { get; set; }
        public string MatrRichiedente_Partecipanti { get; set; }
        public string CodFamiglia_Partecipanti { get; set; }
        public Nullable<int> CodTipoAlloggio_Partecipanti { get; set; }
        public Nullable<int> ProgrAlloggio_Partecipanti { get; set; }
        public string FlagContributo_Partecipanti { get; set; }
        public string DesParentela_Partecipanti { get; set; }
        public string Nominativo_Partecipanti { get; set; }
        public string DataNascita_Partecipanti { get; set; }
        public string Sesso_Partecipanti { get; set; }
        public Nullable<int> Eta_Partecipanti { get; set; }
        public string MatrPagante_Partecipanti { get; set; }
        public string CategoriaArcal_Partecipanti { get; set; }
        public string TipoOspite_Partecipanti { get; set; }
        public string DesAlloggio_Partecipanti { get; set; }
        public string UserID_Partecipanti { get; set; }
        public string DataOraUpd_Partecipanti { get; set; }
        public string CatArcalOrig_Partecipanti { get; set; }
    }
}
