//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TStruttura
    {
        public string tipo_schema { get; set; }
        public string codice_struttura { get; set; }
        public int id_sezione { get; set; }
        public string data_inizio_validita { get; set; }
        public string data_fine_validita { get; set; }
    }
}
