//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSVRuoliEsperProd
    {
        public decimal IdRuoloEsperProd { get; set; }
        public decimal IdEsperProd { get; set; }
        public string CodRuolo { get; set; }
        public string RuoloPrincipale { get; set; }
        public string TipoAgg { get; set; }
        public System.DateTime DataOraAgg { get; set; }
        public string FlagExtraRai { get; set; }
        public string Stato { get; set; }
    }
}
