//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTFR_ENTEPREVCOMPL
    {
        public string CODICE_ENTEPREVCOMPL { get; set; }
        public string DESCR_ENTEPREVCOMPL { get; set; }
        public string INDIRIZZO_ENTEPREVCOMPL { get; set; }
        public string DATAAUTO_ENTEPREVCOMPL { get; set; }
        public string DATAISCR_ENTEPREVCOMPL { get; set; }
        public string FORMAGIUR_ENTEPREVCOMPL { get; set; }
        public string DESCBREVE_ENTEPREVCOMPL { get; set; }
        public string TIPODIP_ENTEPREVCOMPL { get; set; }
    }
}
