//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TXLoginDB2
    {
        public string MATRICOLA { get; set; }
        public string IDENTIFICATIVO { get; set; }
        public string PSSW { get; set; }
        public string FLAG_CESSATO { get; set; }
        public string DATA_ULTIMO_AGG { get; set; }
        public string UTENTE { get; set; }
        public string DATAGG { get; set; }
        public string TIPAGG { get; set; }
        public string PROFILO { get; set; }
        public string DIV_RECLUTA { get; set; }
        public string MATRICOLASEI { get; set; }
    }
}
