//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCOMPETENZE
    {
        public string MATRICOLA { get; set; }
        public string TIPO { get; set; }
        public System.DateTime DATA_ATTIVAZIONE { get; set; }
        public string TIPO_AREA { get; set; }
        public Nullable<System.DateTime> DATA_SCADENZA { get; set; }
        public string CODICE { get; set; }
    }
}
