//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDOCUMENTO_PROCURA
    {
        public string ID_DOC { get; set; }
        public System.DateTime DATA_DOC { get; set; }
        public string IMMAGINE { get; set; }
    }
}
