//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDSocieta
    {
        public string Codice { get; set; }
        public string Data_scadenza { get; set; }
        public string Tipo { get; set; }
        public string Descrizione { get; set; }
        public string DescrBreve { get; set; }
        public Nullable<int> Posizione { get; set; }
        public string DescrLunga { get; set; }
    }
}
