//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRai.Data.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAnagPers
    {
        public string Matricola { get; set; }
        public string Data_decorrenza { get; set; }
        public string Tipo_variazione { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public string Cognome_acquisito { get; set; }
        public string Data_nascita { get; set; }
        public string Comune_nascita { get; set; }
        public string Prov_nascita { get; set; }
        public string Sesso { get; set; }
        public string Codice_fiscale { get; set; }
        public string Stato_civile { get; set; }
        public string Collocamento_obbli { get; set; }
        public string Posizione_militare { get; set; }
    }
}
