//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRai.Data.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCVBox_V2
    {
        public int Id_box { get; set; }
        public string Titolo { get; set; }
        public string Sottotitolo { get; set; }
        public string Stile { get; set; }
        public string Colore { get; set; }
        public string Icona { get; set; }
        public string Link { get; set; }
        public Nullable<int> Posizione { get; set; }
        public Nullable<int> Coefficiente { get; set; }
        public string Obbligatorio { get; set; }
        public string NomeTabella { get; set; }
        public string TitoloAggiungi { get; set; }
        public string FunzioniAggiungi { get; set; }
    }
}
