//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRai.Data.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCVConInfo
    {
        public string Matricola { get; set; }
        public string CodConInfo { get; set; }
        public int Prog { get; set; }
        public string CodConInfoLiv { get; set; }
        public string AltraConInfo { get; set; }
        public string Note { get; set; }
        public string Stato { get; set; }
        public string TipoAgg { get; set; }
        public Nullable<System.DateTime> DataOraAgg { get; set; }
    }
}
