//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRai.Data.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDipendenti
    {
        public string Matricola { get; set; }
        public string Data_inizio_validita { get; set; }
        public string Data_fine_validita { get; set; }
        public string Nominativo { get; set; }
        public string Data_assunzione { get; set; }
        public string Data_cessazione { get; set; }
        public Nullable<int> Sede { get; set; }
        public string Divisione { get; set; }
        public string Tipo_dipendente { get; set; }
        public string Ordine_tipodip { get; set; }
        public string Servizio { get; set; }
        public string TI_TD { get; set; }
        public string Sezione { get; set; }
        public string Responsabile_sez { get; set; }
        public string Categoria { get; set; }
        public string Data_anzianita_categoria { get; set; }
        public string Mansione { get; set; }
        public string Tipo_minimo { get; set; }
        public string Forma_contratto { get; set; }
        public string Indennita_106 { get; set; }
        public string Indennita_11B { get; set; }
        public string Indennita_11C { get; set; }
        public string Indennita_11D { get; set; }
        public string Indennita_11E { get; set; }
        public string Indennita_133 { get; set; }
        public string Indennita_153 { get; set; }
        public string Tipo_variazione { get; set; }
        public string Data_inizio_contabile { get; set; }
        public string Data_fine_contabile { get; set; }
        public string Flag_distacco { get; set; }
        public string Tipo_reclutamento { get; set; }
        public Nullable<int> Sky_sezione { get; set; }
        public string Flag_organico { get; set; }
        public string Flag_responsabile { get; set; }
        public string Data_nascita { get; set; }
        public string Societa { get; set; }
        public string Sesso { get; set; }
        public string Flag_ultimo_record { get; set; }
        public string Figura_pro { get; set; }
    }
}
