//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRai.Data.CurriculumVitae
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSezione
    {
        public int id { get; set; }
        public string descrizione_breve { get; set; }
        public string data_inizio_validita { get; set; }
        public string data_inizio_contabile { get; set; }
        public string data_fine_validita { get; set; }
        public string data_fine_contabile { get; set; }
        public string codice_visibile { get; set; }
        public string data_formalizza { get; set; }
        public string data_convalida { get; set; }
        public string mission { get; set; }
        public string descrizione_lunga { get; set; }
        public Nullable<decimal> num_ordina { get; set; }
        public string attivita { get; set; }
        public string indirizzo { get; set; }
        public string area { get; set; }
        public string sede_contabile { get; set; }
        public string servizio { get; set; }
        public string tel_internazionale { get; set; }
    }
}
