//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Codice sorgente generato automaticamente da xsd, versione=4.6.1055.0.
// 
namespace Models.Smartworking {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0", IsNullable=false)]
    public partial class CreaComunicazione_Input {
        
        private SezioneDatoreLavoro sezioneDatoreLavoroField;
        
        private SezioneLavoratore sezioneLavoratoreField;
        
        private SezioneRapportoLavoro_Crea sezioneRapportoLavoroField;
        
        private SezioneAccordoSmartWorking sezioneAccordoSmartWorkingField;
        
        private SezioneSoggettoAbilitato_Input sezioneSoggettoAbilitatoField;
        
        private string codTipologiaComunicazioneField;
        
        /// <remarks/>
        public SezioneDatoreLavoro SezioneDatoreLavoro {
            get {
                return this.sezioneDatoreLavoroField;
            }
            set {
                this.sezioneDatoreLavoroField = value;
            }
        }
        
        /// <remarks/>
        public SezioneLavoratore SezioneLavoratore {
            get {
                return this.sezioneLavoratoreField;
            }
            set {
                this.sezioneLavoratoreField = value;
            }
        }
        
        /// <remarks/>
        public SezioneRapportoLavoro_Crea SezioneRapportoLavoro {
            get {
                return this.sezioneRapportoLavoroField;
            }
            set {
                this.sezioneRapportoLavoroField = value;
            }
        }
        
        /// <remarks/>
        public SezioneAccordoSmartWorking SezioneAccordoSmartWorking {
            get {
                return this.sezioneAccordoSmartWorkingField;
            }
            set {
                this.sezioneAccordoSmartWorkingField = value;
            }
        }
        
        /// <remarks/>
        public SezioneSoggettoAbilitato_Input SezioneSoggettoAbilitato {
            get {
                return this.sezioneSoggettoAbilitatoField;
            }
            set {
                this.sezioneSoggettoAbilitatoField = value;
            }
        }
        
        /// <remarks/>
        public string CodTipologiaComunicazione {
            get {
                return this.codTipologiaComunicazioneField;
            }
            set {
                this.codTipologiaComunicazioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    public partial class SezioneDatoreLavoro {
        
        private string codiceFiscaleDatoreLavoroField;
        
        private string denominazioneDatoreLavoroField;
        
        /// <remarks/>
        public string CodiceFiscaleDatoreLavoro {
            get {
                return this.codiceFiscaleDatoreLavoroField;
            }
            set {
                this.codiceFiscaleDatoreLavoroField = value;
            }
        }
        
        /// <remarks/>
        public string DenominazioneDatoreLavoro {
            get {
                return this.denominazioneDatoreLavoroField;
            }
            set {
                this.denominazioneDatoreLavoroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    public partial class SezioneAccordoSmartWorking_Input {
        
        private System.DateTime dataSottoscrizioneAccordoField;
        
        private System.DateTime dataInizioPeriodoField;
        
        private System.DateTime dataFinePeriodoField;
        
        private bool dataFinePeriodoFieldSpecified;
        
        private string tipologiaDurataPeriodoField;
        
        /// <remarks/>
        public System.DateTime DataSottoscrizioneAccordo {
            get {
                return this.dataSottoscrizioneAccordoField;
            }
            set {
                this.dataSottoscrizioneAccordoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataInizioPeriodo {
            get {
                return this.dataInizioPeriodoField;
            }
            set {
                this.dataInizioPeriodoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataFinePeriodo {
            get {
                return this.dataFinePeriodoField;
            }
            set {
                this.dataFinePeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataFinePeriodoSpecified {
            get {
                return this.dataFinePeriodoFieldSpecified;
            }
            set {
                this.dataFinePeriodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TipologiaDurataPeriodo {
            get {
                return this.tipologiaDurataPeriodoField;
            }
            set {
                this.tipologiaDurataPeriodoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    public partial class SezioneRapportoLavoro_Modifica {
        
        private string codTipologiaRapportoLavoroField;
        
        private string posizioneINAILField;
        
        private string tariffaINAILField;
        
        /// <remarks/>
        public string CodTipologiaRapportoLavoro {
            get {
                return this.codTipologiaRapportoLavoroField;
            }
            set {
                this.codTipologiaRapportoLavoroField = value;
            }
        }
        
        /// <remarks/>
        public string PosizioneINAIL {
            get {
                return this.posizioneINAILField;
            }
            set {
                this.posizioneINAILField = value;
            }
        }
        
        /// <remarks/>
        public string TariffaINAIL {
            get {
                return this.tariffaINAILField;
            }
            set {
                this.tariffaINAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    public partial class SezioneSoggettoAbilitato_Input {
        
        private string codTipologiaSoggettoAbilitatoField;
        
        private string codiceFiscaleSoggettoAbilitatoField;
        
        /// <remarks/>
        public string CodTipologiaSoggettoAbilitato {
            get {
                return this.codTipologiaSoggettoAbilitatoField;
            }
            set {
                this.codTipologiaSoggettoAbilitatoField = value;
            }
        }
        
        /// <remarks/>
        public string CodiceFiscaleSoggettoAbilitato {
            get {
                return this.codiceFiscaleSoggettoAbilitatoField;
            }
            set {
                this.codiceFiscaleSoggettoAbilitatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    public partial class SezioneAccordoSmartWorking {
        
        private System.DateTime dataSottoscrizioneAccordoField;
        
        private System.DateTime dataInizioPeriodoField;
        
        private System.DateTime dataFinePeriodoField;
        
        private bool dataFinePeriodoFieldSpecified;
        
        private string tipologiaDurataPeriodoField;
        
        private byte[] streamPDFField;
        
        /// <remarks/>
        public System.DateTime DataSottoscrizioneAccordo {
            get {
                return this.dataSottoscrizioneAccordoField;
            }
            set {
                this.dataSottoscrizioneAccordoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataInizioPeriodo {
            get {
                return this.dataInizioPeriodoField;
            }
            set {
                this.dataInizioPeriodoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataFinePeriodo {
            get {
                return this.dataFinePeriodoField;
            }
            set {
                this.dataFinePeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataFinePeriodoSpecified {
            get {
                return this.dataFinePeriodoFieldSpecified;
            }
            set {
                this.dataFinePeriodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TipologiaDurataPeriodo {
            get {
                return this.tipologiaDurataPeriodoField;
            }
            set {
                this.tipologiaDurataPeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] StreamPDF {
            get {
                return this.streamPDFField;
            }
            set {
                this.streamPDFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    public partial class SezioneRapportoLavoro_Crea {
        
        private System.DateTime dataInizioRapportoLavoroField;
        
        private string codTipologiaRapportoLavoroField;
        
        private string posizioneINAILField;
        
        private string tariffaINAILField;
        
        /// <remarks/>
        public System.DateTime DataInizioRapportoLavoro {
            get {
                return this.dataInizioRapportoLavoroField;
            }
            set {
                this.dataInizioRapportoLavoroField = value;
            }
        }
        
        /// <remarks/>
        public string CodTipologiaRapportoLavoro {
            get {
                return this.codTipologiaRapportoLavoroField;
            }
            set {
                this.codTipologiaRapportoLavoroField = value;
            }
        }
        
        /// <remarks/>
        public string PosizioneINAIL {
            get {
                return this.posizioneINAILField;
            }
            set {
                this.posizioneINAILField = value;
            }
        }
        
        /// <remarks/>
        public string TariffaINAIL {
            get {
                return this.tariffaINAILField;
            }
            set {
                this.tariffaINAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    public partial class SezioneLavoratore {
        
        private string codiceFiscaleLavoratoreField;
        
        private string nomeLavoratoreField;
        
        private string cognomeLavoratoreField;
        
        private System.DateTime dataNascitaLavoratoreField;
        
        private string codComuneNascitaLavoratoreField;
        
        /// <remarks/>
        public string CodiceFiscaleLavoratore {
            get {
                return this.codiceFiscaleLavoratoreField;
            }
            set {
                this.codiceFiscaleLavoratoreField = value;
            }
        }
        
        /// <remarks/>
        public string NomeLavoratore {
            get {
                return this.nomeLavoratoreField;
            }
            set {
                this.nomeLavoratoreField = value;
            }
        }
        
        /// <remarks/>
        public string CognomeLavoratore {
            get {
                return this.cognomeLavoratoreField;
            }
            set {
                this.cognomeLavoratoreField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataNascitaLavoratore {
            get {
                return this.dataNascitaLavoratoreField;
            }
            set {
                this.dataNascitaLavoratoreField = value;
            }
        }
        
        /// <remarks/>
        public string CodComuneNascitaLavoratore {
            get {
                return this.codComuneNascitaLavoratoreField;
            }
            set {
                this.codComuneNascitaLavoratoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0", IsNullable=false)]
    public partial class ModificaComunicazione_Input {
        
        private string codiceComunicazioneField;
        
        private SezioneRapportoLavoro_Modifica sezioneRapportoLavoroField;
        
        private SezioneAccordoSmartWorking_Input sezioneAccordoSmartWorkingField;
        
        private SezioneSoggettoAbilitato_Input sezioneSoggettoAbilitatoField;
        
        private string codTipologiaComunicazioneField;
        
        /// <remarks/>
        public string CodiceComunicazione {
            get {
                return this.codiceComunicazioneField;
            }
            set {
                this.codiceComunicazioneField = value;
            }
        }
        
        /// <remarks/>
        public SezioneRapportoLavoro_Modifica SezioneRapportoLavoro {
            get {
                return this.sezioneRapportoLavoroField;
            }
            set {
                this.sezioneRapportoLavoroField = value;
            }
        }
        
        /// <remarks/>
        public SezioneAccordoSmartWorking_Input SezioneAccordoSmartWorking {
            get {
                return this.sezioneAccordoSmartWorkingField;
            }
            set {
                this.sezioneAccordoSmartWorkingField = value;
            }
        }
        
        /// <remarks/>
        public SezioneSoggettoAbilitato_Input SezioneSoggettoAbilitato {
            get {
                return this.sezioneSoggettoAbilitatoField;
            }
            set {
                this.sezioneSoggettoAbilitatoField = value;
            }
        }
        
        /// <remarks/>
        public string CodTipologiaComunicazione {
            get {
                return this.codTipologiaComunicazioneField;
            }
            set {
                this.codTipologiaComunicazioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://mlps.gov.it/DataModels/InformationDelivery/SmartWorking/1.0", IsNullable=false)]
    public partial class AnnullaComunicazione_Input {
        
        private string codiceComunicazioneField;
        
        private SezioneSoggettoAbilitato_Input sezioneSoggettoAbilitatoField;
        
        private string codTipologiaComunicazioneField;
        
        /// <remarks/>
        public string CodiceComunicazione {
            get {
                return this.codiceComunicazioneField;
            }
            set {
                this.codiceComunicazioneField = value;
            }
        }
        
        /// <remarks/>
        public SezioneSoggettoAbilitato_Input SezioneSoggettoAbilitato {
            get {
                return this.sezioneSoggettoAbilitatoField;
            }
            set {
                this.sezioneSoggettoAbilitatoField = value;
            }
        }
        
        /// <remarks/>
        public string CodTipologiaComunicazione {
            get {
                return this.codTipologiaComunicazioneField;
            }
            set {
                this.codTipologiaComunicazioneField = value;
            }
        }
    }
}
