//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMINFOANAG
    {
        public int ID_CMEVENTO { get; set; }
        public Nullable<decimal> PRC_INVALIDITA { get; set; }
        public string CSF_CFSPERSONA { get; set; }
        public string COD_CITTANASC { get; set; }
        public string COD_STCIV { get; set; }
        public string DES_COGNOMEPERS { get; set; }
        public string COD_CATPROT { get; set; }
        public string DES_NOMEPERS { get; set; }
        public string COD_POSMIL { get; set; }
        public string COD_CITTAD { get; set; }
        public string COD_SESSO { get; set; }
        public string DES_COGNOMEACQ { get; set; }
        public string COD_STUDIO { get; set; }
        public string COD_TESSERASAN { get; set; }
        public string IND_PATENTE { get; set; }
        public string COD_TIPOPATENTE { get; set; }
        public Nullable<System.DateTime> DTA_STUDIO { get; set; }
        public Nullable<System.DateTime> DTA_FINELIBRETTOSAN { get; set; }
        public Nullable<System.DateTime> DTA_NASCITAPERS { get; set; }
        public string COD_LIBRETTOLAV { get; set; }
        public Nullable<System.DateTime> DTA_LIBRETTOLAV { get; set; }
        public string COD_CITTALIBRETTO { get; set; }
        public string COD_PAGAMENTO { get; set; }
        public string COD_CONTOCORR { get; set; }
        public string COD_ABI { get; set; }
        public string COD_CAB { get; set; }
        public string COD_CIN { get; set; }
        public string DES_INDIRRES { get; set; }
        public string COD_CITTARES { get; set; }
        public string CAP_CAPRES { get; set; }
        public string DES_TELRES { get; set; }
        public string DES_INDIRDOM { get; set; }
        public string COD_CITTADOM { get; set; }
        public string CAP_CAPDOM { get; set; }
        public string DES_TEL { get; set; }
        public string DES_CELLULARE { get; set; }
        public string DES_EMAIL { get; set; }
        public string IND_FORZCF { get; set; }
        public string COD_CITTASSN { get; set; }
        public string COD_CITTASTUDIO { get; set; }
        public string COD_PUNTEGGIO { get; set; }
        public Nullable<decimal> COD_PUNTEGGIONUM { get; set; }
        public string COD_TIPOPUNTEGGIO { get; set; }
        public Nullable<decimal> COD_LIVELLOPESO { get; set; }
        public string COD_ATENEO { get; set; }
        public string NOT_NOTASTUDIO { get; set; }
        public Nullable<decimal> ID_TPSTRE { get; set; }
        public string DES_HOUSENUMBER { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public string IND_RETTIFICA_RES { get; set; }
        public string IND_SOSTCODFISC { get; set; }
        public string COD_IBAN { get; set; }
        public string COD_NAZ_IBAN { get; set; }
        public string COD_EC_TIPDOC { get; set; }
        public string COD_EC_NUMDOC { get; set; }
        public string COD_EC_PERMESSO { get; set; }
        public Nullable<System.DateTime> DTA_EC_PERMESSO { get; set; }
        public string COD_CTO_ISTRUZIONE { get; set; }
    }
}
