//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPREL
    {
        public int ID_COMPREL { get; set; }
        public Nullable<int> ID_TRLPER { get; set; }
        public int ID_PERSONA { get; set; }
        public System.DateTime DTA_INIZIO { get; set; }
        public System.DateTime DTA_FINE { get; set; }
        public string COD_ATTIVRLAV { get; set; }
        public string COD_TIPORLAV { get; set; }
        public string COD_CATPROT { get; set; }
        public string COD_FINRLAV { get; set; }
        public string COD_IMPRESA { get; set; }
        public string COD_MATLIBROMAT { get; set; }
        public string COD_CID { get; set; }
        public System.DateTime DTA_ANZCONV { get; set; }
        public string NOT_NOTA { get; set; }
        public Nullable<System.DateTime> DTA_ENDTRL { get; set; }
        public System.DateTime DTA_HIRE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    
        public virtual ANAGPERS ANAGPERS { get; set; }
        public virtual JOMPREL JOMPREL { get; set; }
    }
}
