//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CZNMMDOC
    {
        public int ID_CZNMMDOC { get; set; }
        public Nullable<int> ID_DATASOURCE { get; set; }
        public Nullable<int> ID_LANG { get; set; }
        public Nullable<int> ID_DOCSCAT { get; set; }
        public string NME_FILENAME { get; set; }
        public string DES_CZNMMDOC { get; set; }
        public string COD_EXTENSION { get; set; }
        public byte[] OBJ_OBJECT { get; set; }
        public int NBR_FILESIZE { get; set; }
        public string IND_PRIVATE { get; set; }
        public string NME_ATTACHNAME { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    }
}
