//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class JB_COMUNE
    {
        public string COD_CITTA { get; set; }
        public string COD_ISTAT { get; set; }
        public string COD_REGIONE { get; set; }
        public string DES_REGIONE { get; set; }
        public string IND_SOGEI { get; set; }
        public string COD_FLAGA { get; set; }
        public string COD_FLAGB { get; set; }
        public string CAP_CAPCOMUNE { get; set; }
    }
}
