//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class JSSQUAL
    {
        public int ID_ASSQUAL { get; set; }
        public Nullable<System.DateTime> DTA_ANZCAT { get; set; }
        public string COD_TIPOMINIMO { get; set; }
        public string DES_TIPOMINIMO { get; set; }
        public string COD_CLASSESTRAORD { get; set; }
        public string DES_CLASSESTRAORD { get; set; }
    
        public virtual ASSQUAL ASSQUAL { get; set; }
    }
}
