//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQPERSONA
    {
        public int ID_PERSONA { get; set; }
        public string COD_REQUISITO { get; set; }
        public string COD_TIPOREQ { get; set; }
        public Nullable<short> COD_LIVELLOPESO { get; set; }
        public string NOT_NOTABREVE { get; set; }
        public string COD_SOURCE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    }
}
