//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINTESI1
    {
        public SINTESI1()
        {
            this.XR_INC_DIPENDENTI = new HashSet<XR_INC_DIPENDENTI>();
            this.XR_PRV_DIPENDENTI = new HashSet<XR_PRV_DIPENDENTI>();
            this.XR_SERVIZIO = new HashSet<XR_SERVIZIO>();
            this.XR_PRV_LOG = new HashSet<XR_PRV_LOG>();
            this.XR_PRV_OPERSTATI = new HashSet<XR_PRV_OPERSTATI>();
            this.XR_VAL_DELEGATION_PERS = new HashSet<XR_VAL_DELEGATION_PERS>();
            this.XR_VAL_EVALUATION = new HashSet<XR_VAL_EVALUATION>();
            this.XR_VAL_EVALUATOR = new HashSet<XR_VAL_EVALUATOR>();
            this.XR_VAL_OPER_STATE = new HashSet<XR_VAL_OPER_STATE>();
            this.XR_VAL_EVALUATION_NOTE = new HashSet<XR_VAL_EVALUATION_NOTE>();
            this.ASSQUAL_HISTORY = new HashSet<ASSQUAL>();
            this.INCARLAV_HISTORY = new HashSet<INCARLAV>();
            this.XR_SERVIZIO_HISTORY = new HashSet<XR_SERVIZIO>();
            this.EXT_VALUED = new HashSet<XR_VAL_EVALUATOR_EXT>();
            this.EXT_EVALUATOR = new HashSet<XR_VAL_EVALUATOR_EXT>();
            this.STUPERSONA = new HashSet<STUPERSONA>();
            this.XR_INC_OPERSTATI = new HashSet<XR_INC_OPERSTATI>();
            this.MBO_Valutato = new HashSet<XR_MBO_SCHEDA>();
            this.MBO_Responsabile = new HashSet<XR_MBO_SCHEDA>();
            this.XR_INC_DIPENDENTI_NOTE = new HashSet<XR_INC_DIPENDENTI_NOTE>();
            this.XR_INC_DIPENDENTI_NOTE_LAST_MOD = new HashSet<XR_INC_DIPENDENTI_NOTE>();
            this.XR_MBO_SCHEDA_Riporto = new HashSet<XR_MBO_SCHEDA>();
            this.MBO_SecRiporto = new HashSet<XR_MBO_SCHEDA>();
            this.XR_MBO_SCHEDA_Consuntivatore = new HashSet<XR_MBO_SCHEDA>();
        }
    
        public int ID_PERSONA { get; set; }
        public string COD_CITTANASC { get; set; }
        public string DES_CITTANASC { get; set; }
        public string COD_STCIV { get; set; }
        public string DES_STCIV { get; set; }
        public string CSF_CFSPERSONA { get; set; }
        public string DES_TITOLOONOR { get; set; }
        public string DES_COGNOMEPERS { get; set; }
        public string DES_SECCOGNOME { get; set; }
        public string DES_COGNOMEACQ { get; set; }
        public string DES_NOMEPERS { get; set; }
        public Nullable<System.DateTime> DTA_NASCITAPERS { get; set; }
        public string COD_SESSO { get; set; }
        public string COD_POSMIL { get; set; }
        public string DES_POSMIL { get; set; }
        public string DES_CELLULARE { get; set; }
        public string COD_CITTADOM { get; set; }
        public string DES_CITTADOM { get; set; }
        public string DES_TELDOM { get; set; }
        public string CAP_CAPDOM { get; set; }
        public string DES_INDIRDOM { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_RES { get; set; }
        public string COD_CITTARES { get; set; }
        public string DES_CITTARES { get; set; }
        public string DES_TELRESID { get; set; }
        public string CAP_CAPRESID { get; set; }
        public string DES_INDIRRESID { get; set; }
        public Nullable<System.DateTime> DTA_FINE_RES { get; set; }
        public string COD_CITTASTUD { get; set; }
        public string DES_CITTASTUD { get; set; }
        public string COD_STUDIO { get; set; }
        public string DES_STUDIO { get; set; }
        public string COD_PUNTEGGIO { get; set; }
        public Nullable<System.DateTime> DTA_CONSEG { get; set; }
        public string COD_IMPRESA { get; set; }
        public string COD_SOGGETTO { get; set; }
        public string COD_MATLIBROMAT { get; set; }
        public string IND_LIBROMAT { get; set; }
        public Nullable<int> ID_ASSQUAL { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_Q { get; set; }
        public Nullable<System.DateTime> DTA_FINE_Q { get; set; }
        public string COD_QUALIFICA { get; set; }
        public string DES_QUALIFICA { get; set; }
        public Nullable<int> ID_STATO { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_S { get; set; }
        public Nullable<System.DateTime> DTA_FINE_S { get; set; }
        public string COD_STATORAPP { get; set; }
        public string DES_STATORAPP { get; set; }
        public Nullable<int> ID_INCARLAV { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_I { get; set; }
        public Nullable<System.DateTime> DTA_FINE_I { get; set; }
        public Nullable<int> ID_POSTOORG { get; set; }
        public string COD_POSTOORG { get; set; }
        public string DES_NOMEPOSTOORG { get; set; }
        public string IND_RESP { get; set; }
        public Nullable<int> ID_CDCREL { get; set; }
        public Nullable<int> ID_CDC { get; set; }
        public string COD_CDC { get; set; }
        public string DES_CDC { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_CDC { get; set; }
        public Nullable<System.DateTime> DTA_FINE_CDC { get; set; }
        public Nullable<int> ID_TRASF_SEDE { get; set; }
        public string COD_SEDE { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_SEDE { get; set; }
        public Nullable<System.DateTime> DTA_FINE_SEDE { get; set; }
        public string COD_CITTASEDE { get; set; }
        public string DES_CITTASEDE { get; set; }
        public string DES_SEDE { get; set; }
        public string DES_INDIRSEDE { get; set; }
        public string CAP_SEDE { get; set; }
        public string DES_TELSEDE { get; set; }
        public string DES_FAX { get; set; }
        public string DES_ELEMAIL { get; set; }
        public Nullable<int> ID_UNITAORG { get; set; }
        public string COD_UNITAORG { get; set; }
        public string DES_DENOMUNITAORG { get; set; }
        public Nullable<int> ID_JOBASSIGN { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_P { get; set; }
        public Nullable<System.DateTime> DTA_FINE_P { get; set; }
        public string COD_RUOLO { get; set; }
        public string DES_RUOLO { get; set; }
        public Nullable<int> ID_INQUACONTR { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_C { get; set; }
        public Nullable<System.DateTime> DTA_FINE_C { get; set; }
        public Nullable<int> ID_LIVRETR { get; set; }
        public string COD_CONTRRETR { get; set; }
        public string DES_CONTRRETR { get; set; }
        public string COD_LIVRETR { get; set; }
        public string DES_LIVRETR { get; set; }
        public Nullable<int> ID_PRESTEROG { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_M { get; set; }
        public Nullable<System.DateTime> DTA_FINE_M { get; set; }
        public string COD_MODERPRE { get; set; }
        public string DES_MODERPRE { get; set; }
        public Nullable<int> ID_COMPREL { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_CR { get; set; }
        public Nullable<System.DateTime> DTA_FINE_CR { get; set; }
        public Nullable<System.DateTime> DTA_ANZCONV { get; set; }
        public string COD_IMPRESACR { get; set; }
        public string COD_SOGGETTOCR { get; set; }
        public Nullable<int> ID_ASSTPCONTR { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_TPCNTR { get; set; }
        public Nullable<System.DateTime> DTA_FINE_TPCNTR { get; set; }
        public string COD_TPCNTR { get; set; }
        public string DES_TPCNTR { get; set; }
        public Nullable<decimal> ID_XR_SERVIZIO { get; set; }
        public string COD_SERVIZIO { get; set; }
        public string DES_SERVIZIO { get; set; }
        public string COD_EVSERVIZIO { get; set; }
        public string DES_EVSERVIZIO { get; set; }
        public Nullable<System.DateTime> DTA_INIZIO_XR { get; set; }
        public Nullable<System.DateTime> DTA_FINE_XR { get; set; }
    
        public virtual ICollection<XR_INC_DIPENDENTI> XR_INC_DIPENDENTI { get; set; }
        public virtual ICollection<XR_PRV_DIPENDENTI> XR_PRV_DIPENDENTI { get; set; }
        public virtual QUALIFICA QUALIFICA { get; set; }
        public virtual ASSQUAL ASSQUAL { get; set; }
        public virtual ICollection<XR_SERVIZIO> XR_SERVIZIO { get; set; }
        public virtual ICollection<XR_PRV_LOG> XR_PRV_LOG { get; set; }
        public virtual ICollection<XR_PRV_OPERSTATI> XR_PRV_OPERSTATI { get; set; }
        public virtual ICollection<XR_VAL_DELEGATION_PERS> XR_VAL_DELEGATION_PERS { get; set; }
        public virtual ICollection<XR_VAL_EVALUATION> XR_VAL_EVALUATION { get; set; }
        public virtual ICollection<XR_VAL_EVALUATOR> XR_VAL_EVALUATOR { get; set; }
        public virtual ICollection<XR_VAL_OPER_STATE> XR_VAL_OPER_STATE { get; set; }
        public virtual ICollection<XR_VAL_EVALUATION_NOTE> XR_VAL_EVALUATION_NOTE { get; set; }
        public virtual ICollection<ASSQUAL> ASSQUAL_HISTORY { get; set; }
        public virtual ICollection<INCARLAV> INCARLAV_HISTORY { get; set; }
        public virtual INCARLAV INCARLAV { get; set; }
        public virtual ICollection<XR_SERVIZIO> XR_SERVIZIO_HISTORY { get; set; }
        public virtual ICollection<XR_VAL_EVALUATOR_EXT> EXT_VALUED { get; set; }
        public virtual ICollection<XR_VAL_EVALUATOR_EXT> EXT_EVALUATOR { get; set; }
        public virtual ICollection<STUPERSONA> STUPERSONA { get; set; }
        public virtual ICollection<XR_INC_OPERSTATI> XR_INC_OPERSTATI { get; set; }
        public virtual ICollection<XR_MBO_SCHEDA> MBO_Valutato { get; set; }
        public virtual ICollection<XR_MBO_SCHEDA> MBO_Responsabile { get; set; }
        public virtual ICollection<XR_INC_DIPENDENTI_NOTE> XR_INC_DIPENDENTI_NOTE { get; set; }
        public virtual ICollection<XR_INC_DIPENDENTI_NOTE> XR_INC_DIPENDENTI_NOTE_LAST_MOD { get; set; }
        public virtual ICollection<XR_MBO_SCHEDA> XR_MBO_SCHEDA_Riporto { get; set; }
        public virtual ICollection<XR_MBO_SCHEDA> MBO_SecRiporto { get; set; }
        public virtual ICollection<XR_MBO_SCHEDA> XR_MBO_SCHEDA_Consuntivatore { get; set; }
    }
}
