//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRGROUP
    {
        public STRGROUP()
        {
            this.R_STRGROUP = new HashSet<R_STRGROUP>();
        }
    
        public int ID_STRGROUP { get; set; }
        public string NME_STRGROUP { get; set; }
        public string DES_STRGROUP { get; set; }
        public System.DateTime DTA_INIZIO { get; set; }
        public System.DateTime DTA_FINE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    
        public virtual ICollection<R_STRGROUP> R_STRGROUP { get; set; }
    }
}
