//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUPERSONA
    {
        public int ID_PERSONA { get; set; }
        public string COD_STUDIO { get; set; }
        public string COD_CITTA { get; set; }
        public string COD_PUNTEGGIO { get; set; }
        public Nullable<short> COD_PUNTEGGIONUM { get; set; }
        public string COD_TIPOPUNTEGGIO { get; set; }
        public Nullable<short> COD_LIVELLOPESO { get; set; }
        public string COD_ATENEO { get; set; }
        public System.DateTime DTA_CONSEG { get; set; }
        public string NOT_NOTABREVE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    
        public virtual SINTESI1 SINTESI1 { get; set; }
        public virtual TB_STUDIO TB_STUDIO { get; set; }
        public virtual TB_COMUNE TB_COMUNE { get; set; }
        public virtual TB_ATENEO TB_ATENEO { get; set; }
        public virtual TB_TPPUNT TB_TPPUNT { get; set; }
        public virtual JTUPERSONA JTUPERSONA { get; set; }
    }
}
