//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LIVSTUD
    {
        public TB_LIVSTUD()
        {
            this.TB_STUDIO = new HashSet<TB_STUDIO>();
        }
    
        public short COD_LIVELLOSTUDIO { get; set; }
        public string DES_LIVELLOSTUDIO { get; set; }
        public short QTA_ORDINE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public string COD_TIPO_ISTRUZIONE { get; set; }
        public string COD_AMBITO_ISTRUZIONE { get; set; }
        public string COD_GRUPPO_TITOLO { get; set; }
        public Nullable<int> PRIORITA { get; set; }
        public string IND_WEBVISIBLE { get; set; }
    
        public virtual ICollection<TB_STUDIO> TB_STUDIO { get; set; }
    }
}
