//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REQUI
    {
        public string COD_REQUISITO { get; set; }
        public string COD_TIPOREQ { get; set; }
        public string COD_REQ_PADRE { get; set; }
        public string COD_TIPOREQ_PADRE { get; set; }
        public string COD_SETTORE { get; set; }
        public string DES_REQUISITO { get; set; }
        public short PRG_SORT { get; set; }
        public string IND_LINGUA { get; set; }
        public string NOT_REQUISITO { get; set; }
        public short QTA_ORDINE { get; set; }
        public string IND_WEBVISIBLE { get; set; }
        public string COD_UPCHAIN { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    }
}
