//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASF_SEDE
    {
        public int ID_TRASF_SEDE { get; set; }
        public System.DateTime DTA_INIZIO { get; set; }
        public int ID_PERSONA { get; set; }
        public string COD_IMPRESA { get; set; }
        public string COD_SEDE { get; set; }
        public string COD_EVTRASF { get; set; }
        public System.DateTime DTA_FINE { get; set; }
        public string NOT_NOTA { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    
        public virtual SEDE SEDE { get; set; }
        public virtual ANAGPERS ANAGPERS { get; set; }
    }
}
