//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COMPREL_CM
    {
        public string NOME { get; set; }
        public string DES_COGNOMEPERS { get; set; }
        public string DES_NOMEPERS { get; set; }
        public string COD_MATLIBROMAT { get; set; }
        public int ID_PERSONA { get; set; }
    }
}
