//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_XR_SOCIETA
    {
        public string CodSoc { get; set; }
        public string DesSoc { get; set; }
        public string CFSoc { get; set; }
        public string IndirizzoSoc { get; set; }
        public string CapSoc { get; set; }
        public string TelSoc { get; set; }
        public string FaxSoc { get; set; }
        public string RagSoc { get; set; }
        public string IvaSoc { get; set; }
        public string RapLegSoc { get; set; }
        public string MailSoc { get; set; }
    }
}
