//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_XR_STR_TSEZIONE
    {
        public int id { get; set; }
        public string descrizione_breve { get; set; }
        public string data_inizio_validita { get; set; }
        public string data_inizio_contabile { get; set; }
        public string data_fine_validita { get; set; }
        public string data_fine_contabile { get; set; }
        public string codice_visibile { get; set; }
        public string data_formalizza { get; set; }
        public string data_convalida { get; set; }
        public string mission { get; set; }
        public string descrizione_lunga { get; set; }
        public Nullable<decimal> num_ordina { get; set; }
        public string attivita { get; set; }
        public string indirizzo { get; set; }
        public string area { get; set; }
        public string sede_contabile { get; set; }
        public string servizio { get; set; }
        public string tel_internazionale { get; set; }
        public string tipo { get; set; }
        public string livello { get; set; }
        public bool pubblicato { get; set; }
        public int max_responsabili { get; set; }
        public string flag_prodotto { get; set; }
    }
}
