//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_XR_IMM_INSERVIZIO
    {
        public string matricola { get; set; }
        public string COD_IMMATRICOLAZIONE { get; set; }
        public Nullable<System.DateTime> data_assunzione { get; set; }
        public int InServizio { get; set; }
    }
}
