//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_ANAGBANCA
    {
        public int ID_XR_ANAGBANCA { get; set; }
        public string COD_ABI { get; set; }
        public string COD_CAB { get; set; }
        public System.DateTime DTA_INIZIO { get; set; }
        public Nullable<System.DateTime> DTA_FINE { get; set; }
        public string DES_RAG_SOCIALE { get; set; }
        public string COD_CITTA { get; set; }
        public string DES_ABICAB_PREC { get; set; }
        public string DES_INDIRIZZO { get; set; }
        public string NOT_NOTA { get; set; }
        public string IND_CHANGED { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public Nullable<System.DateTime> TMS_TIMESTAMP { get; set; }
    
        public virtual TB_COMUNE TB_COMUNE { get; set; }
    }
}
