//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_DEM_DOCUMENTI
    {
        public XR_DEM_DOCUMENTI()
        {
            this.XR_DEM_VERSIONI_DOCUMENTO = new HashSet<XR_DEM_VERSIONI_DOCUMENTO>();
            this.XR_DEM_WKF_OPERSTATI = new HashSet<XR_DEM_WKF_OPERSTATI>();
            this.XR_DEM_NOTE = new HashSet<XR_DEM_NOTE>();
            this.XR_DEM_AZIONI_AUTOMATICHE = new HashSet<XR_DEM_AZIONI_AUTOMATICHE>();
        }
    
        public int Id { get; set; }
        public string Descrizione { get; set; }
        public string Cod_Tipologia_Documentale { get; set; }
        public int Id_Stato { get; set; }
        public Nullable<int> Id_Richiesta { get; set; }
        public System.DateTime DataCreazione { get; set; }
        public string MatricolaCreatore { get; set; }
        public int IdPersonaCreatore { get; set; }
        public string MatricolaDestinatario { get; set; }
        public Nullable<int> IdPersonaDestinatario { get; set; }
        public string MatricolaApprovatore { get; set; }
        public Nullable<int> IdPersonaApprovatore { get; set; }
        public Nullable<System.DateTime> DataApprovazione { get; set; }
        public string MatricolaFirma { get; set; }
        public Nullable<int> IdPersonaFirma { get; set; }
        public Nullable<System.DateTime> DataFirma { get; set; }
        public string NumeroProtocollo { get; set; }
        public string CodiceProtocollatore { get; set; }
        public Nullable<System.DateTime> DataInvioNotifica { get; set; }
        public byte[] TimeStamp { get; set; }
        public int Id_WKF_Tipologia { get; set; }
        public string Note { get; set; }
        public int Id_Tipo_Doc { get; set; }
        public string NotaApprovatore { get; set; }
        public Nullable<System.DateTime> DataRifiuto { get; set; }
        public bool PraticaAttiva { get; set; }
        public Nullable<System.DateTime> DataLettura { get; set; }
        public string MatricolaIncaricato { get; set; }
        public string NotaFirma { get; set; }
        public Nullable<System.DateTime> DataPresaInModifica { get; set; }
        public string MatricolaPresaInModifica { get; set; }
        public string MatricolaVisualizzatore { get; set; }
        public string Prot_Id_Documento { get; set; }
        public Nullable<System.DateTime> DataPresaInCarico { get; set; }
        public string NotaConclusionePratica { get; set; }
        public Nullable<System.DateTime> DataChiusuraPratica { get; set; }
        public string CustomDataJSON { get; set; }
        public Nullable<System.DateTime> DataVisto { get; set; }
        public Nullable<System.DateTime> DataProtocollo { get; set; }
        public string OggettoProtocollo { get; set; }
        public Nullable<int> IdArea { get; set; }
    
        public virtual XR_DEM_STATI XR_DEM_STATI { get; set; }
        public virtual XR_DEM_TIPI_DOCUMENTO XR_DEM_TIPI_DOCUMENTO { get; set; }
        public virtual XR_DEM_TIPOLOGIE_DOCUMENTALI XR_DEM_TIPOLOGIE_DOCUMENTALI { get; set; }
        public virtual XR_RICHIESTE XR_RICHIESTE { get; set; }
        public virtual XR_WKF_TIPOLOGIA XR_WKF_TIPOLOGIA { get; set; }
        public virtual ICollection<XR_DEM_VERSIONI_DOCUMENTO> XR_DEM_VERSIONI_DOCUMENTO { get; set; }
        public virtual ICollection<XR_DEM_WKF_OPERSTATI> XR_DEM_WKF_OPERSTATI { get; set; }
        public virtual XR_MAT_RICHIESTE XR_MAT_RICHIESTE { get; set; }
        public virtual ICollection<XR_DEM_NOTE> XR_DEM_NOTE { get; set; }
        public virtual ICollection<XR_DEM_AZIONI_AUTOMATICHE> XR_DEM_AZIONI_AUTOMATICHE { get; set; }
        public virtual XR_HRIS_DIR_FILTER XR_HRIS_DIR_FILTER { get; set; }
    }
}
