//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_DEM_NOTE
    {
        public int ID { get; set; }
        public int IDDOCUMENTO { get; set; }
        public string TESTONOTA { get; set; }
        public int TIPONOTA { get; set; }
        public System.DateTime DATAINSERIMENTO { get; set; }
        public string MATRICOLA { get; set; }
        public string NOMINATIVO { get; set; }
    
        public virtual XR_DEM_DOCUMENTI XR_DEM_DOCUMENTI { get; set; }
        public virtual XR_DEM_TIPI_NOTE XR_DEM_TIPI_NOTE { get; set; }
    }
}
