//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_DEM_TIPI_NOTE
    {
        public XR_DEM_TIPI_NOTE()
        {
            this.XR_DEM_NOTE = new HashSet<XR_DEM_NOTE>();
        }
    
        public int ID { get; set; }
        public string CODICE { get; set; }
        public string DESCRIZIONE { get; set; }
    
        public virtual ICollection<XR_DEM_NOTE> XR_DEM_NOTE { get; set; }
    }
}
