//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_DEM_STATI
    {
        public XR_DEM_STATI()
        {
            this.XR_RICHIESTE = new HashSet<XR_RICHIESTE>();
            this.XR_DEM_DOCUMENTI = new HashSet<XR_DEM_DOCUMENTI>();
            this.XR_WKF_WORKFLOW_DYNAMIC_STEPS = new HashSet<XR_WKF_WORKFLOW_DYNAMIC_STEPS>();
            this.XR_WKF_WORKFLOW_DYNAMIC_STEPS1 = new HashSet<XR_WKF_WORKFLOW_DYNAMIC_STEPS>();
            this.XR_DEM_AZIONI_AUTOMATICHE = new HashSet<XR_DEM_AZIONI_AUTOMATICHE>();
            this.XR_DEM_AZIONI_AUTOMATICHE1 = new HashSet<XR_DEM_AZIONI_AUTOMATICHE>();
            this.XR_DEM_AZIONI_AUTOMATICHE_TASK = new HashSet<XR_DEM_AZIONI_AUTOMATICHE_TASK>();
            this.XR_DEM_AZIONI_AUTOMATICHE_TASK1 = new HashSet<XR_DEM_AZIONI_AUTOMATICHE_TASK>();
            this.XR_DEM_AZIONI_AUTOMATICHE_TASK2 = new HashSet<XR_DEM_AZIONI_AUTOMATICHE_TASK>();
        }
    
        public int ID_STATO { get; set; }
        public string DESCRIZIONE { get; set; }
    
        public virtual ICollection<XR_RICHIESTE> XR_RICHIESTE { get; set; }
        public virtual ICollection<XR_DEM_DOCUMENTI> XR_DEM_DOCUMENTI { get; set; }
        public virtual ICollection<XR_WKF_WORKFLOW_DYNAMIC_STEPS> XR_WKF_WORKFLOW_DYNAMIC_STEPS { get; set; }
        public virtual ICollection<XR_WKF_WORKFLOW_DYNAMIC_STEPS> XR_WKF_WORKFLOW_DYNAMIC_STEPS1 { get; set; }
        public virtual ICollection<XR_DEM_AZIONI_AUTOMATICHE> XR_DEM_AZIONI_AUTOMATICHE { get; set; }
        public virtual ICollection<XR_DEM_AZIONI_AUTOMATICHE> XR_DEM_AZIONI_AUTOMATICHE1 { get; set; }
        public virtual ICollection<XR_DEM_AZIONI_AUTOMATICHE_TASK> XR_DEM_AZIONI_AUTOMATICHE_TASK { get; set; }
        public virtual ICollection<XR_DEM_AZIONI_AUTOMATICHE_TASK> XR_DEM_AZIONI_AUTOMATICHE_TASK1 { get; set; }
        public virtual ICollection<XR_DEM_AZIONI_AUTOMATICHE_TASK> XR_DEM_AZIONI_AUTOMATICHE_TASK2 { get; set; }
    }
}
