//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_EXAM_SLOT
    {
        public int ID_SLOT { get; set; }
        public int ID_LAB { get; set; }
        public System.DateTime DTA_INIZIO { get; set; }
        public System.DateTime DTA_FINE { get; set; }
        public Nullable<int> ID_RICHIESTA { get; set; }
    }
}
