//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_EXAM_GRUPPI
    {
        public int ID_ASSOC { get; set; }
        public string COD_GRUPPO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public string MATRICOLA { get; set; }
        public string DES_COGNOMEPERS { get; set; }
        public string DES_NOMEPERS { get; set; }
        public Nullable<System.DateTime> DTA_NASCITAPERS { get; set; }
        public string COD_CITTANASCITA { get; set; }
        public string CSF_CFSPERSONA { get; set; }
        public string COD_SESSO { get; set; }
        public string DES_RECAPITO_TEL { get; set; }
        public string DES_EMAIL { get; set; }
        public string COD_SEDE { get; set; }
        public string COD_SERVIZIO { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    }
}
