//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_HRIS_QUAL_FILTER
    {
        public int ID_QUAL_FILTER { get; set; }
        public string COD_QUAL_FILTER { get; set; }
        public string DESCRIPTION { get; set; }
        public string QUAL_INCLUDED { get; set; }
        public string QUAL_EXCLUDED { get; set; }
        public Nullable<int> QUAL_LEVEL { get; set; }
        public Nullable<int> ORDINE { get; set; }
    }
}
