//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_HRIS_REGOLE_VOCI_MENU
    {
        public int ID_REGOLA { get; set; }
        public int ID_VOCE_MENU { get; set; }
        public string TIPO_REGOLA { get; set; }
        public string CONTESTO { get; set; }
        public string LST_MATR_INCL { get; set; }
        public string LST_MATR_EXCL { get; set; }
        public string ABIL_FUNC { get; set; }
        public string ABIL_SUBFUNC { get; set; }
        public string CODE { get; set; }
        public string JSON { get; set; }
        public string NOME_VOCE { get; set; }
    }
}
