//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_HRIS_WIDGET_DA_FARE
    {
        public int Id { get; set; }
        public string MatricolaOperatore { get; set; }
        public string MatricolaDestinatario { get; set; }
        public string Descrizione { get; set; }
        public string Url { get; set; }
        public string Controller { get; set; }
        public string Azione { get; set; }
        public string Parametri { get; set; }
        public string AzioneJavascript { get; set; }
        public string Classe { get; set; }
        public string Style { get; set; }
        public System.DateTime DataInizioValidita { get; set; }
        public System.DateTime DataFineValidita { get; set; }
        public string Note { get; set; }
        public int Tipologia { get; set; }
    }
}
