//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_HRIS_ABIL_MODELLO
    {
        public XR_HRIS_ABIL_MODELLO()
        {
            this.XR_HRIS_ABIL = new HashSet<XR_HRIS_ABIL>();
            this.XR_HRIS_ABIL_ASSOC_MODELLO = new HashSet<XR_HRIS_ABIL_ASSOC_MODELLO>();
        }
    
        public int ID_MODELLO { get; set; }
        public string CODICE { get; set; }
        public string DIR_INCLUSE { get; set; }
        public string DIR_ESCLUSE { get; set; }
        public string CAT_INCLUSE { get; set; }
        public string CAT_ESCLUSE { get; set; }
        public string SEDI_INCLUSE { get; set; }
        public string SEDI_ESCLUSE { get; set; }
        public string TIP_INCLUSE { get; set; }
        public string TIP_ESCLUSE { get; set; }
        public string SOC_INCLUSE { get; set; }
        public string SOC_ESCLUSE { get; set; }
        public string NOT_NOTE { get; set; }
        public bool IND_ATTIVO { get; set; }
        public string GR_CATEGORIE { get; set; }
        public string MATR_INCLUSE { get; set; }
        public string MATR_ESCLUSE { get; set; }
        public string GR_AREA { get; set; }
        public string CONTR_INCLUSI { get; set; }
        public string CONTR_ESCLUSI { get; set; }
    
        public virtual ICollection<XR_HRIS_ABIL> XR_HRIS_ABIL { get; set; }
        public virtual ICollection<XR_HRIS_ABIL_ASSOC_MODELLO> XR_HRIS_ABIL_ASSOC_MODELLO { get; set; }
    }
}
