//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_INC_DIPENDENTI_NOTE
    {
        public int ID_NOTA { get; set; }
        public int ID_DIPENDENTE { get; set; }
        public int ID_PERSONA { get; set; }
        public string NOTA { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public Nullable<int> LAST_MOD_ID_PERSONA { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_TIMESTAMP { get; set; }
        public string NOTA_ORIG { get; set; }
        public string NOT_TAG { get; set; }
        public Nullable<System.DateTime> DTA_INVIO_DIP { get; set; }
    
        public virtual XR_INC_DIPENDENTI XR_INC_DIPENDENTI { get; set; }
        public virtual ANAGPERS ANAGPERS { get; set; }
        public virtual ANAGPERS LAST_MOD_ANAGPERS { get; set; }
        public virtual SINTESI1 SINTESI1 { get; set; }
        public virtual SINTESI1 LAST_MOD_SINTESI11 { get; set; }
    }
}
