//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_INC_EXTRA_ABIL
    {
        public int ID_EXTRA_ABIL { get; set; }
        public string MATRICOLA { get; set; }
        public string COD_FUNZIONE { get; set; }
        public string COD_SUBFUNZIONE { get; set; }
        public string DIR_INCLUSE { get; set; }
        public string DIR_ESCLUSE { get; set; }
        public string CAT_INCLUSE { get; set; }
        public string CAT_ESCLUSE { get; set; }
        public string NOT_NOTE { get; set; }
        public string SEDI_INCLUSE { get; set; }
        public string SEDI_ESCLUSE { get; set; }
        public string TIP_INCLUSE { get; set; }
        public string TIP_ESCLUSE { get; set; }
    }
}
