//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_MAT_CATEGORIA_TASK
    {
        public int ID { get; set; }
        public int ID_CATEGORIA { get; set; }
        public int ID_TASK { get; set; }
        public Nullable<int> STATO_PRATICA { get; set; }
        public Nullable<int> PROGRESSIVO { get; set; }
    
        public virtual XR_MAT_ELENCO_TASK XR_MAT_ELENCO_TASK { get; set; }
        public virtual XR_MAT_CATEGORIE XR_MAT_CATEGORIE { get; set; }
    }
}
