//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_MAT_ARRETRATI_CONIUGE
    {
        public int ID { get; set; }
        public string MATRICOLA_DIPENDENTE { get; set; }
        public string MATRICOLA_SE_CONIUGE_RAI { get; set; }
        public string CODICE_FISCALE_FIGLIO { get; set; }
        public Nullable<System.DateTime> PERIODO_DA { get; set; }
        public Nullable<System.DateTime> PERIODO_A { get; set; }
        public Nullable<decimal> QUANTITA { get; set; }
        public Nullable<System.DateTime> DATA_INSERIMENTO { get; set; }
        public bool CANCELLATO { get; set; }
    }
}
