//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_MAT_CENSIMENTO_CF_ESITO_DICH
    {
        public int ID { get; set; }
        public string CODICE { get; set; }
        public string RISPOSTA { get; set; }
        public string MATRICOLA { get; set; }
        public System.DateTime DATA_CREAZIONE { get; set; }
    }
}
