//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_MAT_CENSIMENTO_CF_CONGEDI_EXTRA
    {
        public int ID { get; set; }
        public string MATRICOLA { get; set; }
        public string CF { get; set; }
        public System.DateTime DATA_NASCITA { get; set; }
        public string NOMINATIVO { get; set; }
        public string GRADO_PARENTELA { get; set; }
        public string CARICO { get; set; }
        public Nullable<int> TOT_MESI_CONIUGE { get; set; }
        public Nullable<decimal> TOT_GIORNI_CONIUGE { get; set; }
        public Nullable<int> TOT_MESI_PRECEDENTI_DIP { get; set; }
        public Nullable<decimal> TOT_GIORNI_PRECEDENTI_DIP { get; set; }
        public string OPZIONE_GRUPPO_A { get; set; }
        public string OPZIONE_GRUPPO_B { get; set; }
        public string OPZIONE_GRUPPO_C { get; set; }
        public string MOTIVO_A3 { get; set; }
        public System.DateTime DATA_ULTIMO_UPDATE { get; set; }
        public string NOTE { get; set; }
        public bool DISABILE { get; set; }
        public Nullable<System.DateTime> DATA_INIZIO_CARICO { get; set; }
        public bool FLAG_EVITA_INSERIMENTO_DATI { get; set; }
        public Nullable<System.DateTime> DATA_AFFIDAMENTO { get; set; }
        public string MATRICOLA_CONIUGE_RAI { get; set; }
        public bool SALVATAGGIO_ANTICIPATO { get; set; }
    }
}
