//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_MAT_PRIVACY_POLICY
    {
        public int ID { get; set; }
        public string TIPO { get; set; }
        public string TESTO_POLICY { get; set; }
        public System.DateTime DATA_INIZIO_VALIDITA { get; set; }
        public System.DateTime DATA_FINE_VALIDITA { get; set; }
    }
}
