//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_MBO_NOTE
    {
        public int ID_NOTA { get; set; }
        public int ID_SCHEDA { get; set; }
        public int ID_TIPOLOGIA { get; set; }
        public string NOT_NOTA { get; set; }
        public int ID_PERSONA { get; set; }
        public string VISIBILITA { get; set; }
        public Nullable<int> ID_PERSONA_DEST { get; set; }
        public Nullable<int> ID_OPERSTATO { get; set; }
        public System.DateTime DTA_INSERIMENTO { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public Nullable<int> ID_OBIETTIVO { get; set; }
    
        public virtual XR_MBO_OPERSTATI XR_MBO_OPERSTATI { get; set; }
        public virtual XR_MBO_SCHEDA XR_MBO_SCHEDA { get; set; }
    }
}
