//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_MAT_CATEGORIE
    {
        public XR_MAT_CATEGORIE()
        {
            this.XR_MAT_CATEGORIA_TASK = new HashSet<XR_MAT_CATEGORIA_TASK>();
            this.XR_MAT_RICHIESTE = new HashSet<XR_MAT_RICHIESTE>();
        }
    
        public int ID { get; set; }
        public string CAT { get; set; }
        public string SOTTO_CAT { get; set; }
        public string TITOLO { get; set; }
        public string SOTTO_TITOLO { get; set; }
        public int ORDINE { get; set; }
        public string CAMPI { get; set; }
        public string ALLEGATI { get; set; }
        public Nullable<int> ID_TIPOLOGIA_WORKFLOW { get; set; }
        public Nullable<int> ID_SCADENZARIO_PANGEA { get; set; }
        public string ECCEZIONE { get; set; }
        public string DESCRIZIONE_ECCEZIONE { get; set; }
        public Nullable<bool> ATTIVA { get; set; }
        public string ESCLUDI_PER_TIPODIP { get; set; }
        public bool UFFPERS_PARALLELO { get; set; }
        public Nullable<bool> DOC_NECESSARIO_ANNULL { get; set; }
        public Nullable<bool> SKIP_FUSIONE_PERIODI { get; set; }
        public string SESSO { get; set; }
        public Nullable<bool> PIANIFICA_ANCHE_9X { get; set; }
        public Nullable<int> ID_MACROCAT { get; set; }
        public string DESCRIZIONE_SOTTOCAT { get; set; }
        public string CODICE_DEMATERIALIZZAZIONE { get; set; }
        public string SOLO_TIPO_DIP { get; set; }
        public string TIPO_AGGIORNAMENTO_STATO { get; set; }
        public Nullable<System.DateTime> DATA_FINE_FORZATA { get; set; }
        public bool ATTIVA_SELF { get; set; }
    
        public virtual ICollection<XR_MAT_CATEGORIA_TASK> XR_MAT_CATEGORIA_TASK { get; set; }
        public virtual XR_MAT_MACROCATEGORIE XR_MAT_MACROCATEGORIE { get; set; }
        public virtual ICollection<XR_MAT_RICHIESTE> XR_MAT_RICHIESTE { get; set; }
    }
}
