//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_MBO_MAIL_LOG
    {
        public int ID_MAIL_LOG { get; set; }
        public int ID_INIZIATIVA { get; set; }
        public int ID_PERSONA { get; set; }
        public System.DateTime DTA_INVIO { get; set; }
        public string MAIL_TESTO { get; set; }
        public string MAIL_OGGETTO { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public string COD_TIPO { get; set; }
    }
}
