//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_NDI_TB_TIPO_RAPPORTO
    {
        public XR_NDI_TB_TIPO_RAPPORTO()
        {
            this.XR_NDI_TIPO_SOGGETTO = new HashSet<XR_NDI_TIPO_SOGGETTO>();
        }
    
        public string COD_TIPOLOGIA { get; set; }
        public string DES_TIPOLOGIA { get; set; }
        public int ORDINE { get; set; }
        public bool IND_MATR_COLLEGATA { get; set; }
        public bool IND_IMPORTO_REDDITO { get; set; }
    
        public virtual ICollection<XR_NDI_TIPO_SOGGETTO> XR_NDI_TIPO_SOGGETTO { get; set; }
    }
}
