//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_PRV_DIREZIONE
    {
        public XR_PRV_DIREZIONE()
        {
            this.XR_PRV_DIREZIONE_PROV = new HashSet<XR_PRV_DIREZIONE_PROV>();
            this.XR_PRV_DIPENDENTI = new HashSet<XR_PRV_DIPENDENTI>();
            this.XR_PRV_CAMPAGNA_DIREZIONE = new HashSet<XR_PRV_CAMPAGNA_DIREZIONE>();
        }
    
        public int ID_DIREZIONE { get; set; }
        public int ID_AREA { get; set; }
        public string CODICE { get; set; }
        public string NOME { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public Nullable<int> ORDINE { get; set; }
        public string PROTOCOLLO { get; set; }
        public Nullable<System.DateTime> VALID_DTA_INI { get; set; }
        public Nullable<System.DateTime> VALID_DTA_END { get; set; }
    
        public virtual ICollection<XR_PRV_DIREZIONE_PROV> XR_PRV_DIREZIONE_PROV { get; set; }
        public virtual ICollection<XR_PRV_DIPENDENTI> XR_PRV_DIPENDENTI { get; set; }
        public virtual XR_PRV_AREA XR_PRV_AREA { get; set; }
        public virtual ICollection<XR_PRV_CAMPAGNA_DIREZIONE> XR_PRV_CAMPAGNA_DIREZIONE { get; set; }
    }
}
