//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_PRV_PROV_IMPORTO
    {
        public int ID_PROV_GRAT { get; set; }
        public int ID_PROV { get; set; }
        public string LIVELLO { get; set; }
        public decimal IMPORTO { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public string CAT_INCLUSE { get; set; }
        public string CAT_ESCLUSE { get; set; }
    
        public virtual XR_PRV_PROV XR_PRV_PROV { get; set; }
    }
}
