//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_PRV_DIPENDENTI_SIMULAZIONI
    {
        public int ID_SIMULAZIONE { get; set; }
        public int ID_DIPENDENTE { get; set; }
        public string MATRICOLA { get; set; }
        public string MATR_RICHIESTA { get; set; }
        public System.DateTime DTA_RICHIESTA { get; set; }
        public string CAT_PARTENZA { get; set; }
        public string CAT_ARRIVO { get; set; }
        public Nullable<System.DateTime> DTA_ESECUZIONE { get; set; }
        public Nullable<System.DateTime> DTA_ACQUISIZIONE { get; set; }
        public string JSON_SIMULAZIONE { get; set; }
        public Nullable<bool> IND_ESITO_ESECUZIONE { get; set; }
        public Nullable<bool> IND_ESITO_ACQUISIZIONE { get; set; }
        public string NOT_ERROR { get; set; }
        public int ROWID_DB2 { get; set; }
    }
}
