//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_PRV_DIPENDENTI_CAUSE
    {
        public int ID_CAUSA { get; set; }
        public string MATRICOLA { get; set; }
        public string STATO { get; set; }
        public string DESCRIZIONE { get; set; }
        public Nullable<System.DateTime> DT_RICHIESTA { get; set; }
        public Nullable<int> ANNO_RICHIESTA { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    }
}
