//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_RECAPITI
    {
        public int ID_RECAPITI { get; set; }
        public int ID_PERSONA { get; set; }
        public System.DateTime DTA_INIZIO { get; set; }
        public System.DateTime DTA_FINE { get; set; }
        public string COD_CITTA { get; set; }
        public string DES_PREFISSO { get; set; }
        public string DES_CELLULARE { get; set; }
        public string TIPO_RECAPITO { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    }
}
