//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_SW_API
    {
        public int ID { get; set; }
        public string MATRICOLA { get; set; }
        public System.DateTime PERIODO_DAL { get; set; }
        public System.DateTime PERIODO_AL { get; set; }
        public string TIPOLOGIA_API { get; set; }
        public string MATRICOLA_OPERATORE { get; set; }
        public System.DateTime DATA_CREAZIONE { get; set; }
        public string JSON_INVIATO { get; set; }
        public Nullable<System.DateTime> DATA_INVIO_API { get; set; }
        public Nullable<System.DateTime> DATA_RISPOSTA_API { get; set; }
        public string JSON_RICEVUTO { get; set; }
        public string CODICE_COMUNICAZIONE_API { get; set; }
        public Nullable<int> ID_STATORAPPORTO { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> ID_RIFERIMENTO_SW_API { get; set; }
        public string ERRORE { get; set; }
    }
}
