//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_TB_HRDOC_TIPOLOGIEDOCUMENTI
    {
        public int ID { get; set; }
        public string MACRO_CATEGORIA { get; set; }
        public string DESCRIZIONE_MACRO_CATEGORIA { get; set; }
        public string TIPOLOGIA { get; set; }
        public string DESCRIZIONE_ESTESA { get; set; }
        public string ECCEZIONI { get; set; }
    }
}
