//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_TB_LOG_BATCH
    {
        public int ID { get; set; }
        public string NOMEBATCH { get; set; }
        public string MATRICOLA { get; set; }
        public System.DateTime DATAOPERAZIONE { get; set; }
        public string PROTOCOLLO { get; set; }
        public string IDDOCUMENTOPROTOCOLLO { get; set; }
        public Nullable<System.DateTime> DATAPROTOCOLLO { get; set; }
        public string OGGETTOPROTOCOLLO { get; set; }
        public bool ESITO { get; set; }
        public string DESCRIZIONE { get; set; }
        public string NOMETEMPLATEUTILIZZATO { get; set; }
        public string NOMEFILEGENERATO { get; set; }
        public string MIMETYPEFILEGENERATO { get; set; }
        public byte[] CONTENTBYTEFILEGENERATO { get; set; }
        public string INFOAGGIUNTIVEJSON { get; set; }
        public System.DateTime DATARIFERIMENTO { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public Nullable<System.DateTime> DATAELABORAZIONEHRDOC { get; set; }
        public string MATRICOLACALLER { get; set; }
        public Nullable<int> IDRIFERIMENTO { get; set; }
        public string TIPOLOGIARIFERIMENTO { get; set; }
    }
}
