//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_VAR_STRAORDINARI
    {
        public int ID_REC_STR { get; set; }
        public int ID_PERSONA { get; set; }
        public string MATRICOLA { get; set; }
        public System.DateTime DTA_COMPETENZA { get; set; }
        public System.DateTime DTA_RIFERIMENTO { get; set; }
        public decimal IMP_IMPORTO { get; set; }
        public System.DateTime DTA_INSERIMENTO { get; set; }
    }
}
