//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_VAL_EVALUATOR
    {
        public XR_VAL_EVALUATOR()
        {
            this.DELEGANTE = new HashSet<XR_VAL_DELEGATION>();
            this.DELEGATO = new HashSet<XR_VAL_DELEGATION>();
            this.XR_VAL_EVALUATION = new HashSet<XR_VAL_EVALUATION>();
            this.EXT_ROLE_ASSIGNED = new HashSet<XR_VAL_EVALUATOR_EXT>();
            this.XR_VAL_EVALUATOR_EXT = new HashSet<XR_VAL_EVALUATOR_EXT>();
        }
    
        public int ID_EVALUATOR { get; set; }
        public int ID_PERSONA { get; set; }
        public int ID_CAMPAIGN { get; set; }
        public System.DateTime VALID_DTA_INI { get; set; }
        public Nullable<System.DateTime> VALID_DTA_END { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public int ID_CAMPAIGN_SHEET { get; set; }
    
        public virtual SINTESI1 SINTESI1 { get; set; }
        public virtual XR_VAL_CAMPAIGN XR_VAL_CAMPAIGN { get; set; }
        public virtual ICollection<XR_VAL_DELEGATION> DELEGANTE { get; set; }
        public virtual ICollection<XR_VAL_DELEGATION> DELEGATO { get; set; }
        public virtual ICollection<XR_VAL_EVALUATION> XR_VAL_EVALUATION { get; set; }
        public virtual XR_VAL_CAMPAIGN_SHEET XR_VAL_CAMPAIGN_SHEET { get; set; }
        public virtual ICollection<XR_VAL_EVALUATOR_EXT> EXT_ROLE_ASSIGNED { get; set; }
        public virtual ICollection<XR_VAL_EVALUATOR_EXT> XR_VAL_EVALUATOR_EXT { get; set; }
    }
}
