//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_VARIAZIONE_TEMP
    {
        public int ID_XR_VARIAZIONE_TEMP { get; set; }
        public int PROG_EVENTO { get; set; }
        public string COD_EVVARTEMP { get; set; }
        public int ID_PERSONA { get; set; }
        public System.DateTime DTA_INIZIO { get; set; }
        public System.DateTime DTA_FINE { get; set; }
        public System.DateTime DTA_INIZIO_TEMP { get; set; }
        public System.DateTime DTA_FINE_TEMP { get; set; }
        public Nullable<int> ID_UNITAORG_TEMP { get; set; }
        public string COD_SERVIZIO_TEMP { get; set; }
        public string COD_SEDE_TEMP { get; set; }
        public Nullable<int> ID_UNITAORG { get; set; }
        public string COD_SERVIZIO { get; set; }
        public string COD_SEDE { get; set; }
        public string NOT_VARIAZIONE { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    }
}
