//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_VAL_DELEGATION
    {
        public XR_VAL_DELEGATION()
        {
            this.XR_VAL_DELEGATION_PERS = new HashSet<XR_VAL_DELEGATION_PERS>();
        }
    
        public int ID_DELEGATION { get; set; }
        public int ID_DELEGATOR { get; set; }
        public int ID_DELEGATE { get; set; }
        public System.DateTime DTA_START { get; set; }
        public System.DateTime DTA_END { get; set; }
        public System.DateTime VALID_DTA_INI { get; set; }
        public Nullable<System.DateTime> VALID_DTA_END { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
    
        public virtual ICollection<XR_VAL_DELEGATION_PERS> XR_VAL_DELEGATION_PERS { get; set; }
        public virtual XR_VAL_EVALUATOR DELEGANTE { get; set; }
        public virtual XR_VAL_EVALUATOR DELEGATO { get; set; }
    }
}
