//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_VAL_EVALUATOR_EXT
    {
        public int ID_EVALUATOR_EXT { get; set; }
        public int ID_EVALUATOR { get; set; }
        public int ID_PERSONA_VALUED { get; set; }
        public int ID_PERSONA_CHOOSEN { get; set; }
        public string NOT_REQUEST { get; set; }
        public Nullable<bool> IND_APPROVED { get; set; }
        public string NOT_APPROVED { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public Nullable<int> ID_EVALUATOR_CHOOSEN { get; set; }
        public System.DateTime VALID_DTA_INI { get; set; }
        public Nullable<System.DateTime> VALID_DTA_END { get; set; }
    
        public virtual SINTESI1 EXT_VALUED { get; set; }
        public virtual SINTESI1 EXT_EVALUATOR { get; set; }
        public virtual XR_VAL_EVALUATOR EXT_ROLE_ASSIGNED { get; set; }
        public virtual XR_VAL_EVALUATOR XR_VAL_EVALUATOR { get; set; }
    }
}
