//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_VAL_PARAM
    {
        public int ID_PARAM { get; set; }
        public string CHIAVE { get; set; }
        public string VALORE1 { get; set; }
        public string VALORE2 { get; set; }
        public string VALORE3 { get; set; }
    }
}
