//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_VAR_DESCRITTIVE
    {
        public int Id { get; set; }
        public string Matricola { get; set; }
        public int Anno { get; set; }
        public int Mese { get; set; }
        public string Descrittiva { get; set; }
        public System.DateTime DataFrom { get; set; }
        public System.DateTime DataTo { get; set; }
        public System.DateTime DataInserimento { get; set; }
        public string RigaCSV { get; set; }
    }
}
