//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRaiData.Incentivi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XR_WKF_OPERSTATI_GENERIC
    {
        public int ID_OPERSTATI { get; set; }
        public int ID_TIPOLOGIA { get; set; }
        public string COD_TIPO_PRATICA { get; set; }
        public int ID_GESTIONE { get; set; }
        public int ID_STATO { get; set; }
        public int ID_PERSONA { get; set; }
        public int DTA_OPERAZIONE { get; set; }
        public System.DateTime VALID_DTA_INI { get; set; }
        public Nullable<System.DateTime> VALID_DTA_END { get; set; }
        public string COD_USER { get; set; }
        public string COD_TERMID { get; set; }
        public System.DateTime TMS_TIMESTAMP { get; set; }
        public string NOMINATIVO { get; set; }
        public bool NASCOSTO { get; set; }
        public Nullable<bool> UFFPERS_PRESA_VISIONE { get; set; }
    
        public virtual XR_WKF_RICHIESTE XR_WKF_RICHIESTE { get; set; }
        public virtual XR_WKF_TIPOLOGIA XR_WKF_TIPOLOGIA { get; set; }
        public virtual XR_WKF_STATI XR_WKF_STATI { get; set; }
    }
}
