//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuliziaLOG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class digiGappEntities : DbContext
    {
        public digiGappEntities()
            : base("name=digiGappEntities")
        {
            var objectContext = ( this as IObjectContextAdapter ).ObjectContext;

            objectContext.CommandTimeout = 600;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LOG> LOG { get; set; }
        public DbSet<MyRai_ParametriSistema> MyRai_ParametriSistema { get; set; }
        public DbSet<MyRai_LogAPI> MyRai_LogAPI { get; set; }
        public DbSet<MyRai_LogAzioni> MyRai_LogAzioni { get; set; }
        public DbSet<MyRai_LogDB> MyRai_LogDB { get; set; }
        public DbSet<MyRai_LogErrori> MyRai_LogErrori { get; set; }
        public DbSet<MyRai_MensaXML> MyRai_MensaXML { get; set; }
    }
}
