//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuliziaLOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRai_LogDB
    {
        public int Id { get; set; }
        public string NomeTabella { get; set; }
        public Nullable<int> IdTabella { get; set; }
        public string Operazione { get; set; }
        public string Modifiche { get; set; }
        public System.DateTime Data { get; set; }
        public string Matricola { get; set; }
    }
}
